import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
import {OBJExporter} from 'three/addons/exporters/OBJExporter.js';
const $=s=>document.querySelector(s),viewport=$('#viewport'),objects=[],templates=new Map(),loader=new OBJLoader();let selected=null,catalog=[],category='すべて';
const undoStack=[];let historyEnabled=false,editActive=false;
function snapshot(){return {selected:objects.indexOf(selected),items:objects.map(o=>{let color; o.traverse(c=>{if(c.isMesh)color=c.material.color.getHex();});return {id:o.userData.shapeId,position:o.position.toArray(),rotation:o.rotation.toArray(),scale:o.scale.toArray(),visible:o.visible,color};})};}
function remember(){if(!historyEnabled)return;const state=snapshot();if(JSON.stringify(undoStack.at(-1)?.items)!==JSON.stringify(state.items)){undoStack.push(state);if(undoStack.length>100)undoStack.shift();}}
function undo(){if(!historyEnabled||transform.dragging)return;const current=JSON.stringify(snapshot().items);let state;while(undoStack.length){const candidate=undoStack.pop();if(JSON.stringify(candidate.items)!==current){state=candidate;break;}}if(!state){$('#status').textContent='これ以上戻せません';return;}historyEnabled=false;select(null);for(const o of objects){scene.remove(o);o.traverse(c=>{if(c.isMesh)c.material.dispose();});}objects.length=0;try{for(const item of state.items){const o=create(item.id,new T.Vector3().fromArray(item.position));o.visible=item.visible!==false;o.rotation.fromArray(item.rotation);o.scale.fromArray(item.scale);o.traverse(c=>{if(c.isMesh)c.material.color.setHex(item.color);});}select(objects[state.selected]??null);refreshCount();$('#status').textContent='ひとつ前の操作に戻しました';}finally{historyEnabled=true;editActive=false;}}
function beginEdit(){if(!editActive){remember();editActive=true;}}
for(const container of [$('#fields'),$('#color')]){container.addEventListener('input',beginEdit,true);container.addEventListener('change',()=>{editActive=false;});container.addEventListener('focusout',()=>{editActive=false;});}
const scene=new T.Scene();scene.background=new T.Color('#edf0f7');const camera=new T.PerspectiveCamera(42,1,.05,500);camera.position.set(11,10,13);
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});}catch(e){$('#loading').textContent='3D表示を開始できませんでした。WebGL対応のブラウザで開いてください。';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;viewport.append(renderer.domElement);
scene.add(new T.HemisphereLight(0xffffff,0xc3c8db,2.5));const sun=new T.DirectionalLight(0xffffff,3);sun.position.set(8,15,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25});sun.shadow.bias=-.0003;scene.add(sun);
const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#edf0f7',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.035;floor.receiveShadow=true;scene.add(floor);let grid=new T.GridHelper(100,100,0x9ca8c2,0xc8cfdf);grid.position.y=-.02;scene.add(grid);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=false;orbit.maxPolarAngle=Math.PI;orbit.mouseButtons={LEFT:null,MIDDLE:T.MOUSE.PAN,RIGHT:null};
const transform=new TransformControls(camera,renderer.domElement);transform.setSize(.8);scene.add(transform.getHelper());transform.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value;});transform.addEventListener('objectChange',()=>{if(selected){for(const a of ['x','y','z'])selected.scale[a]=Math.max(.01,selected.scale[a]);syncFields();}});
const box=new T.BoxHelper(new T.Object3D(),0x9173f5);box.visible=false;scene.add(box);
transform.addEventListener('mouseDown',remember);
new ResizeObserver(()=>{const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe(viewport);
renderer.setAnimationLoop(()=>{orbit.update();if(selected)box.setFromObject(selected);renderer.render(scene,camera);});
const groups=[['position','位置','m'],['rotation','角度','°'],['scale','大きさ','倍率']];
for(const [key,name,unit]of groups){const section=document.createElement('div');section.className='field-group';section.innerHTML=`<h3>${name}<span>${unit}</span></h3><div class="coords">${['x','y','z'].map(a=>`<label><span>${a.toUpperCase()}</span><input type="number" id="${key}-${a}" aria-label="${name} ${a.toUpperCase()}" step="${key==='rotation'?5:.1}" ${key==='scale'?'min="0.01"':''}></label>`).join('')}</div>`;$('#fields').append(section);for(const a of ['x','y','z'])$('#'+key+'-'+a).addEventListener('change',e=>{if(!selected)return;const val=Number(e.target.value);if(!Number.isFinite(val)||e.target.value===''||(key==='scale'&&val<=0)){syncFields();return;}selected[key][a]=key==='rotation'?T.MathUtils.degToRad(val):key==='position'?snapPosition(val):val;syncFields();});}
for(const [key]of groups)for(const a of ['x','y','z'])$('#'+key+'-'+a).addEventListener('input',e=>{if(!selected||e.target.value==='')return;const n=Number(e.target.value);if(Number.isFinite(n)&&(key!=='scale'||n>0))selected[key][a]=key==='rotation'?T.MathUtils.degToRad(n):n;});
function syncFields(){if(!selected)return;for(const [key]of groups)for(const a of ['x','y','z']){const v=key==='rotation'?T.MathUtils.radToDeg(selected[key][a]):selected[key][a];$('#'+key+'-'+a).value=Number(v.toFixed(3));}}
function select(o){selected=o;renderParts();$('#empty').hidden=!!o;$('#properties').hidden=!o;box.visible=!!o;if(!o){transform.detach();return;}if(o.visible)transform.attach(o);else transform.detach();box.visible=o.visible;box.setFromObject(o);$('#selectedName').textContent=o.userData.label;let color; o.traverse(c=>{if(c.isMesh)color=c.material.color;});$('#color').value='#'+color.getHexString();syncFields();}
function refreshCount(){$('#count').textContent=objects.length+' オブジェクト';renderParts();}
function create(id,position){const item=catalog.find(v=>v.id===id);if(!item||!templates.has(id))throw Error('この形はありません');remember();const o=templates.get(id).clone(true);o.traverse(c=>{if(c.isMesh){c.material=new T.MeshStandardMaterial({color:'#9c88ec',roughness:.62,metalness:.03});c.castShadow=true;c.receiveShadow=true;}});o.userData={shapeId:id,label:item.name};o.position.copy(position??new T.Vector3(Math.round(orbit.target.x),0,Math.round(orbit.target.z)));if(historyEnabled&&$('#snap').checked){for(const a of ['x','y','z'])o.position[a]=snapPosition(o.position[a]);}scene.add(o);objects.push(o);select(o);refreshCount();$('#status').textContent=item.name+'を追加しました';return o;}
function remove(){if(!selected)return;remember();const old=selected;select(null);scene.remove(old);objects.splice(objects.indexOf(old),1);old.traverse(c=>{if(c.isMesh)c.material.dispose();});refreshCount();$('#status').textContent='形を削除しました';}
function duplicate(){if(!selected)return;const old=selected;const o=create(old.userData.shapeId,old.position.clone().add(new T.Vector3(1,0,1)));o.rotation.copy(old.rotation);o.scale.copy(old.scale);let color;old.traverse(c=>{if(c.isMesh)color=c.material.color;});o.traverse(c=>{if(c.isMesh)c.material.color.copy(color);});select(o);}
function mode(m){transform.setMode(m);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));$('#delete').onclick=remove;$('#duplicate').onclick=duplicate;$('#focus').onclick=()=>{if(!selected)return;const b=new T.Box3().setFromObject(selected),center=b.getCenter(new T.Vector3()),size=b.getSize(new T.Vector3()).length();orbit.target.copy(center);camera.position.copy(center).add(new T.Vector3(1,.8,1).normalize().multiplyScalar(Math.max(4,size*1.8)));};$('#color').oninput=e=>{selected?.traverse(c=>{if(c.isMesh)c.material.color.set(e.target.value);});};
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>{if(!objects.length){$('#status').textContent='まず形を追加してください';return;}const group=new T.Group();for(const o of objects)group.add(o.clone(true));download('rippy-world.obj',new OBJExporter().parse(group));$('#status').textContent='ワールドの形状をOBJで保存しました（色は含みません）';};$('#singleObj').onclick=()=>{if(selected)download('rippy-'+selected.userData.shapeId+'.obj',new OBJExporter().parse(selected));};
let pointerStart;renderer.domElement.addEventListener('pointerdown',e=>{pointerStart={x:e.clientX,y:e.clientY,axis:transform.axis};});renderer.domElement.addEventListener('pointerup',e=>{if(e.button!==0||!pointerStart||pointerStart.axis||transform.dragging||Math.hypot(pointerStart.x-e.clientX,pointerStart.y-e.clientY)>5)return;const r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(objects.filter(o=>o.visible),true)[0];if(hit){let o=hit.object;while(o.parent&&o.parent!==scene)o=o.parent;select(o);}else select(null);});
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||e.ctrlKey||e.metaKey)return;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}if(e.key.toLowerCase()==='w')mode('translate');if(e.key.toLowerCase()==='e')mode('rotate');if(e.key.toLowerCase()==='r')mode('scale');});
window.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)||e.altKey||e.shiftKey||e.key.toLowerCase()!=='z')return;const active=document.activeElement;if(active?.isContentEditable||active?.matches('textarea, input:not([type="number"]):not([type="color"])'))return;e.preventDefault();undo();});

function renderParts(){const list=$('#parts');if(!list)return;list.replaceChildren();objects.forEach((o,i)=>{const row=document.createElement('div');row.className='part-row'+(o===selected?' selected':'');const pick=document.createElement('button');pick.textContent=(i+1)+'. '+o.userData.label;pick.setAttribute('aria-pressed',String(o===selected));pick.onclick=()=>select(o);const visibility=document.createElement('button');visibility.textContent=o.visible?'表示':'非表示';visibility.setAttribute('aria-label',o.userData.label+' '+(i+1)+' の表示切り替え');visibility.setAttribute('aria-pressed',String(o.visible));visibility.onclick=()=>{remember();o.visible=!o.visible;select(selected);};row.append(pick,visibility);list.append(row);});}
function applySnap(){const enabled=$('#snap').checked,step=Number($('#snap-step').value);transform.setTranslationSnap(enabled?step:null);transform.setRotationSnap(enabled?T.MathUtils.degToRad(15):null);transform.setScaleSnap(enabled?.1:null);$('#status').textContent=enabled?'スナップ：移動 '+step+' m / 回転 15° / サイズ 0.1倍':'スナップ OFF';}
function snapPosition(value){if(!$('#snap').checked)return value;const step=Number($('#snap-step').value);return Number((Math.round(value/step)*step).toFixed(8));}
function updateGrid(){const step=Number($('#snap-step').value);scene.remove(grid);grid.geometry.dispose();for(const m of Array.isArray(grid.material)?grid.material:[grid.material])m.dispose();grid=new T.GridHelper(100,Math.round(100/step),0x9ca8c2,0xc8cfdf);grid.position.y=-.02;grid.visible=$('#grid-visible').checked;scene.add(grid);applySnap();}
$('#grid-visible').onchange=()=>{grid.visible=$('#grid-visible').checked;$('#status').textContent=grid.visible?'グリッドを表示しました':'グリッドを非表示にしました';};
$('#snap').onchange=applySnap;$('#snap-step').onchange=updateGrid;applySnap();
const views={front:[0,0,1],back:[0,0,-1],right:[1,0,0],left:[-1,0,0],top:[0,1,.00001],bottom:[0,-1,.00001],home:[1,.8,1]};
document.querySelectorAll('[data-view]').forEach(b=>{b.onclick=()=>{const distance=Math.max(2,camera.position.distanceTo(orbit.target));camera.position.copy(orbit.target).add(new T.Vector3(...views[b.dataset.view]).normalize().multiplyScalar(distance));orbit.update();$('#status').textContent=b.textContent+'から表示';};});

function renderCatalog(){const search=$('#search').value.trim().toLowerCase();$('#catalog').replaceChildren();const items=catalog.filter(v=>(category==='すべて'||v.category===category)&&v.name.toLowerCase().includes(search));for(const v of items){const b=document.createElement('button');b.className='shape';b.dataset.id=v.id;b.title=v.name+'を追加';b.innerHTML=`<img src="thumbnails/${v.id}.svg" alt="" loading="lazy"><span>${v.name}</span>`;b.onclick=()=>create(v.id);$('#catalog').append(b);}if(!items.length)$('#catalog').textContent='見つかりませんでした';}
$('#search').oninput=renderCatalog;
async function start(){catalog=await fetch('./catalog.json').then(r=>{if(!r.ok)throw Error('catalog');return r.json();});await Promise.all(catalog.map(async v=>{const g=await loader.loadAsync(v.file);templates.set(v.id,g);}));for(const name of ['すべて',...new Set(catalog.map(v=>v.category))]){const b=document.createElement('button');b.textContent=name;b.className=name===category?'active':'';b.onclick=()=>{category=name;$('#categories').querySelectorAll('button').forEach(v=>v.classList.toggle('active',v===b));renderCatalog();};$('#categories').append(b);}renderCatalog();$('#loading').hidden=true;
const base=create('003',new T.Vector3(0,0,0));base.scale.set(3.8,2,3.8);base.traverse(c=>{if(c.isMesh)c.material.color.set('#b7a9f3');});const cube=create('001',new T.Vector3(-1.6,.27,0));cube.scale.set(.8,.8,.8);const cone=create('007',new T.Vector3(1.4,.27,-.6));cone.traverse(c=>{if(c.isMesh)c.material.color.set('#eac07a');});const ball=create('004',new T.Vector3(.8,.27,1.6));ball.scale.set(.65,.65,.65);ball.traverse(c=>{if(c.isMesh)c.material.color.set('#7fc7ba');});select(cube);$('#status').textContent='形を選んで、自由に組み立てよう';
if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'add_shape',description:'ライブラリの形をワールドに追加する',inputSchema:{type:'object',properties:{id:{type:'string',pattern:'^[0-9]{3}$'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(typeof input?.id!=='string'||!templates.has(input.id))throw Error('Invalid shape id');const o=create(input.id);return {shapeId:o.userData.shapeId,count:objects.length};}});}catch(e){console.warn('WebMCP registration unavailable',e);}}
historyEnabled=true;window.rippy={catalog,objects,create,select,scene,templates};}
start().catch(e=>{console.error(e);$('#loading').hidden=false;$('#loading').textContent='形の読み込みに失敗しました。ページを再読み込みしてください。';});

