import {initGameStudio} from './game-studio.js?v=20260925-smooth1';
import * as T from 'three';
import {centerPivot,offsetGeometry} from './center-pivot.js?v=20260925-smooth1';
import {validateFace,makeExtrusion} from './sketch-geometry.js?v=20260925-smooth1';
import {subtractObjects} from './solid-subtract.js?v=20260925-smooth1';
import {makeSweep} from './sweep-geometry.js?v=20260925-smooth1';
import {makeRevolve} from './revolve-geometry.js?v=20260925-smooth1';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
import {OBJExporter} from 'three/addons/exporters/OBJExporter.js';
const $=s=>document.querySelector(s),viewport=$('#viewport'),objects=[],templates=new Map(),loader=new OBJLoader();let selected=null,catalog=[],category='すべて';
const selection=new Set(),selectionBoxes=[];let moveOrigin=new T.Vector3();
const undoStack=[];let historyEnabled=false,editActive=false;
function encode(o){const data={position:o.position.toArray(),rotation:o.rotation.toArray(),scale:o.scale.toArray(),visible:o.visible,label:o.userData.label,pivotOffset:o.userData.pivotOffset};if(o.userData.isJoined)data.children=o.children.map(encode);else{data.id=o.userData.shapeId;if(o.userData.revolve)data.revolve=o.userData.revolve;if(o.userData.sweep)data.sweep=o.userData.sweep;if(o.userData.csg)data.geometry=o.geometry.toJSON();if(o.userData.sketch)data.sketch=o.userData.sketch;data.colors=[];o.traverse(c=>{if(c.isMesh)data.colors.push(c.material.color.getHex());});}return data;}
function decode(data){let o;if(data.children){o=new T.Group();o.userData={isJoined:true,label:data.label};data.children.forEach(c=>o.add(decode(c)));}else{o=data.revolve?new T.Mesh(makeRevolve(data.revolve)):data.sweep?new T.Mesh(makeSweep(data.sweep)):data.geometry?new T.Mesh(new T.BufferGeometryLoader().parse(data.geometry)):data.sketch?new T.Mesh(makeExtrusion(data.sketch.points,data.sketch.distance)):templates.get(data.id).clone(true);o.userData={shapeId:data.id,label:data.label,...(data.revolve?{revolve:structuredClone(data.revolve)}:{}),...(data.sweep?{sweep:structuredClone(data.sweep)}:{}),...(data.geometry?{csg:true}:{}),...(data.sketch?{sketch:structuredClone(data.sketch)}:{})};let i=0;o.traverse(c=>{if(c.isMesh){c.material=new T.MeshStandardMaterial({color:data.colors[i++],roughness:.62,metalness:.03});c.castShadow=true;c.receiveShadow=true;}});}if(data.pivotOffset){if(!data.geometry)offsetGeometry(o,new T.Vector3().fromArray(data.pivotOffset));o.userData.pivotOffset=[...data.pivotOffset];}o.position.fromArray(data.position);o.rotation.fromArray(data.rotation);o.scale.fromArray(data.scale);o.visible=data.visible;return o;}
function snapshot(){return {selected:[...selection].map(o=>objects.indexOf(o)),items:objects.map(encode)};}
function remember(){if(!historyEnabled)return;const state=snapshot();if(JSON.stringify(undoStack.at(-1)?.items)!==JSON.stringify(state.items)){undoStack.push(state);if(undoStack.length>100)undoStack.shift();}}
function undo(){if(!historyEnabled||transform.dragging)return;const current=JSON.stringify(snapshot().items);let state;while(undoStack.length){const candidate=undoStack.pop();if(JSON.stringify(candidate.items)!==current){state=candidate;break;}}if(!state){$('#status').textContent='これ以上戻せません';return;}historyEnabled=false;select(null);for(const o of objects){scene.remove(o);o.traverse(c=>{if(c.isMesh){c.material.dispose();if(c.userData.sketch||c.userData.csg||c.userData.sweep||c.userData.pivotOwned||c.userData.revolve)c.geometry.dispose();}});}objects.length=0;try{for(const item of state.items){const o=decode(item);scene.add(o);objects.push(o);}setSelection(state.selected.map(i=>objects[i]).filter(Boolean));refreshCount();$('#status').textContent='ひとつ前の操作に戻しました';}finally{historyEnabled=true;editActive=false;}}
function beginEdit(){if(!editActive){remember();editActive=true;}}
for(const container of [$('#fields'),$('#color'),$('#move-delta')]){container.addEventListener('input',beginEdit,true);container.addEventListener('change',()=>{editActive=false;});container.addEventListener('focusout',()=>{editActive=false;});}
const scene=new T.Scene();scene.background=new T.Color('#edf0f7');const camera=new T.PerspectiveCamera(42,1,.05,500);camera.position.set(11,10,13);
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});}catch(e){$('#loading').textContent='3D表示を開始できませんでした。WebGL対応のブラウザで開いてください。';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;viewport.append(renderer.domElement);
scene.add(new T.HemisphereLight(0xffffff,0xc3c8db,2.5));const sun=new T.DirectionalLight(0xffffff,3);sun.position.set(8,15,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25});sun.shadow.bias=-.0003;scene.add(sun);
const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#edf0f7',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.035;floor.receiveShadow=true;scene.add(floor);let grid=new T.GridHelper(100,100,0x9ca8c2,0xc8cfdf);grid.position.y=-.02;scene.add(grid);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=false;orbit.maxPolarAngle=Math.PI;orbit.mouseButtons={LEFT:null,MIDDLE:T.MOUSE.PAN,RIGHT:null};
const transform=new TransformControls(camera,renderer.domElement);transform.setSize(.8);scene.add(transform.getHelper());transform.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value;});transform.addEventListener('objectChange',()=>{if(selected){for(const a of ['x','y','z'])selected.scale[a]=Math.max(.01,selected.scale[a]);syncFields();}});
const box=new T.BoxHelper(new T.Object3D(),0x9173f5);box.visible=false;scene.add(box);
transform.addEventListener('mouseDown',()=>{remember();if(selected&&transform.getMode()==='translate'){moveOrigin.copy(selected.position);syncFields();}});
new ResizeObserver(()=>{const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe(viewport);
renderer.setAnimationLoop(()=>{orbit.update();if(selected)box.setFromObject(selected);for(const helper of selectionBoxes)helper.update();renderer.render(scene,camera);});
const groups=[['position','位置','m'],['rotation','角度','°'],['scale','大きさ','倍率']];
for(const [key,name,unit]of groups){const section=document.createElement('div');section.className='field-group';section.innerHTML=`<h3>${name}<span>${unit}</span></h3><div class="coords">${['x','y','z'].map(a=>`<label><span>${a.toUpperCase()}</span><input type="number" id="${key}-${a}" aria-label="${name} ${a.toUpperCase()}" step="${key==='rotation'?5:.1}" ${key==='scale'?'min="0.01"':''}></label>`).join('')}</div>`;$('#fields').append(section);for(const a of ['x','y','z'])$('#'+key+'-'+a).addEventListener('change',e=>{if(!selected)return;const val=Number(e.target.value);if(!Number.isFinite(val)||e.target.value===''||(key==='scale'&&val<=0)){syncFields();return;}if(key==='rotation')centerPivot(selected);selected[key][a]=key==='rotation'?T.MathUtils.degToRad(val):key==='position'?snapPosition(val):val;syncFields();});}
for(const [key]of groups)for(const a of ['x','y','z'])$('#'+key+'-'+a).addEventListener('input',e=>{if(!selected||e.target.value==='')return;const n=Number(e.target.value);if(Number.isFinite(n)&&(key!=='scale'||n>0)){if(key==='rotation')centerPivot(selected);selected[key][a]=key==='rotation'?T.MathUtils.degToRad(n):n;}});
function syncFields(){if(!selected)return;syncMoveDelta();for(const [key]of groups)for(const a of ['x','y','z']){const v=key==='rotation'?T.MathUtils.radToDeg(selected[key][a]):selected[key][a];$('#'+key+'-'+a).value=Number(v.toFixed(3));}}
function select(o,additive=false){if(additive){const next=new Set(selection);if(next.has(o))next.delete(o);else if(o)next.add(o);setSelection([...next]);}else setSelection(o?[o]:[]);}
function setSelection(items){selection.clear();items.forEach(o=>selection.add(o));selected=items.at(-1)??null;if(selected){if(transform.getMode()==='rotate')centerPivot(selected);moveOrigin.copy(selected.position);for(const a of ['x','y','z'])$('#delta-'+a).value=0;}for(const helper of selectionBoxes){scene.remove(helper);helper.geometry.dispose();helper.material.dispose();}selectionBoxes.length=0;renderParts();const multiple=selection.size>1;$('#empty').hidden=!!selected;$('#properties').hidden=!selected;$('#fields').hidden=multiple;$('#move-delta').hidden=multiple;$('#color').parentElement.hidden=false;$('#join').disabled=!multiple;$('#hole').disabled=!multiple;$('#hole-help').hidden=!multiple;if(multiple)$('#hole-help').textContent='穴あけ：残す形「'+items[0].userData.label+'」／型 '+(items.length-1)+' 個（型は処理後に削除）';box.visible=!!selected&&selected.visible;transform.detach();if(!selected)return;$('#selectedName').textContent=multiple?selection.size+' 個を選択中':selected.userData.label;$('#singleObj').textContent=multiple?'↓ 選択した形のOBJを保存':'↓ この形のOBJを保存';if(!multiple&&selected.visible)transform.attach(selected);for(const o of items){if(o!==selected&&o.visible){const helper=new T.BoxHelper(o,0x9173f5);scene.add(helper);selectionBoxes.push(helper);}}box.setFromObject(selected);let color;selected.traverse(c=>{if(c.isMesh)color=c.material.color;});if(color)$('#color').value='#'+color.getHexString();syncFields();}
function refreshCount(){$('#count').textContent=objects.length+' オブジェクト';renderParts();}
function create(id,position){const item=catalog.find(v=>v.id===id);if(!item||!templates.has(id))throw Error('この形はありません');remember();const o=templates.get(id).clone(true);o.traverse(c=>{if(c.isMesh){c.material=new T.MeshStandardMaterial({color:'#9c88ec',roughness:.62,metalness:.03});c.castShadow=true;c.receiveShadow=true;}});o.userData={shapeId:id,label:item.name};o.position.copy(position??new T.Vector3(Math.round(orbit.target.x),0,Math.round(orbit.target.z)));if(historyEnabled&&$('#snap').checked){for(const a of ['x','y','z'])o.position[a]=snapPosition(o.position[a]);}scene.add(o);objects.push(o);select(o);refreshCount();$('#status').textContent=item.name+'を追加しました';return o;}
function remove(){if(!selection.size)return;remember();const targets=[...selection];select(null);for(const o of targets){scene.remove(o);objects.splice(objects.indexOf(o),1);o.traverse(c=>{if(c.isMesh){c.material.dispose();if(c.userData.sketch||c.userData.csg||c.userData.sweep||c.userData.pivotOwned||c.userData.revolve)c.geometry.dispose();}});}refreshCount();$('#status').textContent=targets.length+' 個を削除しました';}

let objectClipboard=null,pasteNumber=0;
function copySelection(){if(!selection.size){$('#status').textContent='コピーする形を選択してください';return;}objectClipboard=structuredClone([...selection].map(encode));pasteNumber=0;$('#status').textContent=objectClipboard.length+' 個をコピーしました（Ctrl+Vで貼り付け）';}
function pasteSelection(){if(!objectClipboard?.length){$('#status').textContent='先に形を選んでCtrl+Cでコピーしてください';return;}const copies=[];try{for(const data of objectClipboard)copies.push(decode(data));}catch(e){for(const o of copies)o.traverse(c=>{if(c.isMesh){c.material.dispose();if(c.userData.sketch||c.userData.csg||c.userData.sweep||c.userData.pivotOwned||c.userData.revolve)c.geometry.dispose();}});$('#status').textContent='貼り付けに失敗しました。コピーし直してください';return;}remember();pasteNumber++;for(const o of copies){o.position.add(new T.Vector3(pasteNumber,0,pasteNumber));scene.add(o);objects.push(o);}setSelection(copies);refreshCount();$('#status').textContent=copies.length+' 個を貼り付けました（Ctrl+Zで戻せます）';}
function canCopyObjects(){const active=document.activeElement;return historyEnabled&&!transform.dragging&&!document.querySelector('dialog[open]')&&!active?.isContentEditable&&!active?.matches('input,textarea,select');}
document.addEventListener('copy',e=>{if(!canCopyObjects())return;copySelection();if(selection.size&&e.clipboardData){e.clipboardData.setData('text/plain','Rippy 3D Studio: '+selection.size+' objects');e.preventDefault();}});
document.addEventListener('paste',e=>{if(!canCopyObjects())return;e.preventDefault();pasteSelection();});

function duplicate(){if(!selection.size)return;remember();const copies=[...selection].map(old=>{const o=decode(encode(old));o.position.add(new T.Vector3(1,0,1));scene.add(o);objects.push(o);return o;});setSelection(copies);refreshCount();$('#status').textContent=copies.length+' 個を複製しました';}
function join(){if(selection.size<2)return;remember();const members=[...selection];const bounds=new T.Box3();members.forEach(o=>bounds.union(new T.Box3().setFromObject(o)));const group=new T.Group();group.userData={isJoined:true,label:'結合（'+members.length+' パーツ）'};bounds.getCenter(group.position);scene.add(group);group.updateMatrixWorld(true);for(const o of members){group.attach(o);objects.splice(objects.indexOf(o),1);}objects.push(group);select(group);refreshCount();$('#status').textContent='結合しました。一つのグループとして移動・複製・削除できます';}
$('#join').onclick=join;
$('#hole').onclick=()=>{if(selection.size<2)return;const targets=[...selection];try{const resultMeshes=subtractObjects(targets[0],targets.slice(1));remember();let result=null;if(resultMeshes.length){result=new T.Group();result.userData={isJoined:true,label:'穴あけ（'+targets[0].userData.label+'）'};resultMeshes.forEach(m=>result.add(m));const center=new T.Box3().setFromObject(result).getCenter(new T.Vector3());resultMeshes.forEach(m=>m.geometry.translate(-center.x,-center.y,-center.z));result.position.copy(center);}select(null);for(const o of targets){scene.remove(o);objects.splice(objects.indexOf(o),1);o.traverse(c=>{if(c.isMesh){c.material.dispose();if(c.userData.sketch||c.userData.csg||c.userData.sweep||c.userData.pivotOwned||c.userData.revolve)c.geometry.dispose();}});}if(result){scene.add(result);objects.push(result);select(result);}refreshCount();$('#status').textContent=result?'重なった部分をくり抜きました（Ctrl+Zで戻せます）':'全体が削れました（Ctrl+Zで戻せます）';}catch(e){$('#status').textContent=e.message;}};
function mode(m){if(m==='rotate'&&selected){centerPivot(selected);moveOrigin.copy(selected.position);syncFields();}transform.setMode(m);if(m==='translate'&&selected){moveOrigin.copy(selected.position);syncFields();}document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));$('#delete').onclick=remove;$('#duplicate').onclick=duplicate;$('#focus').onclick=()=>{if(!selected)return;const b=new T.Box3().setFromObject(selected),center=b.getCenter(new T.Vector3()),size=b.getSize(new T.Vector3()).length();orbit.target.copy(center);camera.position.copy(center).add(new T.Vector3(1,.8,1).normalize().multiplyScalar(Math.max(4,size*1.8)));};$('#color').oninput=e=>{for(const o of selection)o.traverse(c=>{if(c.isMesh)c.material.color.set(e.target.value);});};
function syncMoveDelta(){for(const a of ['x','y','z']){const input=$('#delta-'+a);if(document.activeElement!==input)input.value=Number((selected.position[a]-moveOrigin[a]).toFixed(4));}}
for(const a of ['x','y','z']){const input=$('#delta-'+a);input.addEventListener('input',()=>{if(!selected||selection.size!==1||input.value==='')return;const n=Number(input.value);if(!Number.isFinite(n))return;selected.position[a]=moveOrigin[a]+n;syncFields();});input.addEventListener('change',()=>{if(!selected)return;if(input.value===''||!Number.isFinite(Number(input.value)))input.value=Number((selected.position[a]-moveOrigin[a]).toFixed(4));});input.addEventListener('keydown',e=>{if(e.key==='Enter')input.blur();});}
$('#reset-delta').onclick=()=>{if(selected){moveOrigin.copy(selected.position);for(const a of ['x','y','z'])$('#delta-'+a).value=0;$('#status').textContent='現在の位置を移動量の基準にしました';}};
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>{if(!objects.length){$('#status').textContent='まず形を追加してください';return;}const group=new T.Group();for(const o of objects)group.add(o.clone(true));download('rippy-world.obj',new OBJExporter().parse(group));$('#status').textContent='ワールドの形状をOBJで保存しました（色は含みません）';};$('#singleObj').onclick=()=>{if(!selection.size)return;const group=new T.Group();for(const o of selection)group.add(o.clone(true));download('rippy-selection.obj',new OBJExporter().parse(group));};
const marquee=document.createElement('div');marquee.className='selection-marquee';marquee.hidden=true;viewport.append(marquee);let pointerStart;
renderer.domElement.addEventListener('pointerdown',e=>{if(document.body.classList.contains('playing')||e.button!==0)return;pointerStart={x:e.clientX,y:e.clientY,axis:transform.axis,shift:e.shiftKey,id:e.pointerId};});
window.addEventListener('pointermove',e=>{const p=pointerStart;if(!p||p.id!==e.pointerId||p.axis||transform.dragging)return;if(Math.hypot(p.x-e.clientX,p.y-e.clientY)<5)return;const r=renderer.domElement.getBoundingClientRect();marquee.hidden=false;Object.assign(marquee.style,{left:Math.min(p.x,e.clientX)-r.left+'px',top:Math.min(p.y,e.clientY)-r.top+'px',width:Math.abs(p.x-e.clientX)+'px',height:Math.abs(p.y-e.clientY)+'px'});});
window.addEventListener('pointercancel',()=>{pointerStart=null;marquee.hidden=true;});
window.addEventListener('pointerup',e=>{const p=pointerStart;if(!p||e.pointerId!==p.id||e.button!==0)return;pointerStart=null;marquee.hidden=true;if(p.axis||transform.dragging)return;const r=renderer.domElement.getBoundingClientRect();if(Math.hypot(p.x-e.clientX,p.y-e.clientY)>5){const left=Math.min(p.x,e.clientX),right=Math.max(p.x,e.clientX),top=Math.min(p.y,e.clientY),bottom=Math.max(p.y,e.clientY);scene.updateMatrixWorld(true);const hits=objects.filter(o=>{if(!o.visible)return false;const bounds=new T.Box3().setFromObject(o);if(bounds.isEmpty())return false;for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const v=new T.Vector3(x,y,z).project(camera),sx=r.left+(v.x+1)*r.width/2,sy=r.top+(1-v.y)*r.height/2;if(v.z< -1||v.z>1||sx<left||sx>right||sy<top||sy>bottom)return false;}return true;});setSelection(p.shift?[...new Set([...selection,...hits])]:hits);$('#status').textContent=selection.size+' 個を範囲選択しました';return;}const ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(objects.filter(o=>o.visible),true)[0];if(hit){let o=hit.object;while(o.parent&&o.parent!==scene)o=o.parent;select(o,p.shift);}else if(!p.shift)select(null);});
window.addEventListener('keydown',e=>{if(document.body.classList.contains('playing')||document.querySelector('dialog[open]'))return;if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||e.ctrlKey||e.metaKey)return;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}if(e.key.toLowerCase()==='w')mode('translate');if(e.key.toLowerCase()==='e')mode('rotate');if(e.key.toLowerCase()==='r')mode('scale');});
window.addEventListener('keydown',e=>{if(document.body.classList.contains('playing')||document.querySelector('dialog[open]'))return;if(!(e.ctrlKey||e.metaKey)||e.altKey||e.shiftKey||e.key.toLowerCase()!=='z')return;const active=document.activeElement;if(active?.isContentEditable||active?.matches('textarea, input:not([type="number"]):not([type="color"])'))return;e.preventDefault();undo();});

function renderParts(){const list=$('#parts');if(!list)return;list.replaceChildren();objects.forEach((o,i)=>{const row=document.createElement('div');row.className='part-row'+(selection.has(o)?' selected':'');const pick=document.createElement('button');pick.textContent=(i+1)+'. '+o.userData.label;pick.setAttribute('aria-pressed',String(selection.has(o)));pick.onclick=e=>select(o,e.shiftKey);const visibility=document.createElement('button');visibility.textContent=o.visible?'表示':'非表示';visibility.setAttribute('aria-label',o.userData.label+' '+(i+1)+' の表示切り替え');visibility.setAttribute('aria-pressed',String(o.visible));visibility.onclick=()=>{remember();o.visible=!o.visible;setSelection([...selection]);};row.append(pick,visibility);list.append(row);});}
function applySnap(){const enabled=$('#snap').checked,step=Number($('#snap-step').value);transform.setTranslationSnap(enabled?step:null);transform.setRotationSnap(enabled?T.MathUtils.degToRad(15):null);transform.setScaleSnap(enabled?.1:null);$('#status').textContent=enabled?'スナップ：移動 '+step+' m / 回転 15° / サイズ 0.1倍':'スナップ OFF';}
function snapPosition(value){if(!$('#snap').checked)return value;const step=Number($('#snap-step').value);return Number((Math.round(value/step)*step).toFixed(8));}
function updateGrid(){const step=Number($('#snap-step').value);scene.remove(grid);grid.geometry.dispose();for(const m of Array.isArray(grid.material)?grid.material:[grid.material])m.dispose();grid=new T.GridHelper(100,Math.round(100/step),0x9ca8c2,0xc8cfdf);grid.position.y=-.02;grid.visible=$('#grid-visible').checked;scene.add(grid);applySnap();}
$('#grid-visible').onchange=()=>{grid.visible=$('#grid-visible').checked;$('#status').textContent=grid.visible?'グリッドを表示しました':'グリッドを非表示にしました';};
$('#snap').onchange=applySnap;$('#snap-step').onchange=updateGrid;applySnap();

const cubeSurface=$('.cube-faces');let cubeDrag=null,suppressCubeClick=false;
cubeSurface.title='ドラッグでカメラを回転・面をクリックして視点を切り替え';
cubeSurface.addEventListener('pointerdown',e=>{if(e.button!==0||transform.dragging)return;suppressCubeClick=false;cubeDrag={id:e.pointerId,x:e.clientX,y:e.clientY,start:new T.Spherical().setFromVector3(camera.position.clone().sub(orbit.target)),moved:false};});
cubeSurface.addEventListener('pointermove',e=>{const d=cubeDrag;if(!d||d.id!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(!d.moved&&Math.hypot(dx,dy)<4)return;if(!d.moved){d.moved=true;cubeSurface.setPointerCapture(e.pointerId);cubeSurface.classList.add('dragging');}e.preventDefault();const spherical=d.start.clone();spherical.theta-=dx*.012;spherical.phi=Math.max(.00001,Math.min(Math.PI-.00001,d.start.phi-dy*.012));camera.position.copy(orbit.target).add(new T.Vector3().setFromSpherical(spherical));orbit.update();$('#status').textContent='ビューキューブでカメラを回転中';});
function endCubeDrag(e){if(!cubeDrag||cubeDrag.id!==e.pointerId)return;suppressCubeClick=cubeDrag.moved;if(cubeDrag.moved)$('#status').textContent='カメラの向きを変更しました';cubeDrag=null;cubeSurface.classList.remove('dragging');if(cubeSurface.hasPointerCapture(e.pointerId))cubeSurface.releasePointerCapture(e.pointerId);}
cubeSurface.addEventListener('pointerup',endCubeDrag);cubeSurface.addEventListener('pointercancel',endCubeDrag);cubeSurface.addEventListener('lostpointercapture',e=>{if(cubeDrag?.id===e.pointerId){cubeDrag=null;cubeSurface.classList.remove('dragging');}});
cubeSurface.addEventListener('click',e=>{if(suppressCubeClick&&e.detail!==0){e.preventDefault();e.stopImmediatePropagation();suppressCubeClick=false;}},true);

const views={front:[0,0,1],back:[0,0,-1],right:[1,0,0],left:[-1,0,0],top:[0,1,.00001],bottom:[0,-1,.00001],home:[1,.8,1]};
document.querySelectorAll('[data-view]').forEach(b=>{b.onclick=()=>{const distance=Math.max(2,camera.position.distanceTo(orbit.target));camera.position.copy(orbit.target).add(new T.Vector3(...views[b.dataset.view]).normalize().multiplyScalar(distance));orbit.update();$('#status').textContent=b.textContent+'から表示';};});

function renderCatalog(){const search=$('#search').value.trim().toLowerCase();$('#catalog').replaceChildren();const items=catalog.filter(v=>(category==='すべて'||v.category===category)&&v.name.toLowerCase().includes(search));for(const v of items){const b=document.createElement('button');b.className='shape';b.dataset.id=v.id;b.title=v.name+'を追加';b.innerHTML=`<img src="thumbnails/${v.id}.svg" alt="" loading="lazy"><span>${v.name}</span>`;b.onclick=()=>create(v.id);$('#catalog').append(b);}if(!items.length)$('#catalog').textContent='見つかりませんでした';}
$('#search').oninput=renderCatalog;
async function start(){catalog=await fetch('./catalog.json').then(r=>{if(!r.ok)throw Error('catalog');return r.json();});await Promise.all(catalog.map(async v=>{const g=await loader.loadAsync(v.file);templates.set(v.id,g);}));for(const name of ['すべて',...new Set(catalog.map(v=>v.category))]){const b=document.createElement('button');b.textContent=name;b.className=name===category?'active':'';b.onclick=()=>{category=name;$('#categories').querySelectorAll('button').forEach(v=>v.classList.toggle('active',v===b));renderCatalog();};$('#categories').append(b);}renderCatalog();$('#loading').hidden=true;
const base=create('003',new T.Vector3(0,0,0));base.scale.set(3.8,2,3.8);base.traverse(c=>{if(c.isMesh)c.material.color.set('#b7a9f3');});const cube=create('001',new T.Vector3(-1.6,.27,0));cube.scale.set(.8,.8,.8);const cone=create('007',new T.Vector3(1.4,.27,-.6));cone.traverse(c=>{if(c.isMesh)c.material.color.set('#eac07a');});const ball=create('004',new T.Vector3(.8,.27,1.6));ball.scale.set(.65,.65,.65);ball.traverse(c=>{if(c.isMesh)c.material.color.set('#7fc7ba');});select(cube);$('#status').textContent='形を選んで、自由に組み立てよう';
if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'add_shape',description:'ライブラリの形をワールドに追加する',inputSchema:{type:'object',properties:{id:{type:'string',pattern:'^[0-9]{3}$'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(typeof input?.id!=='string'||!templates.has(input.id))throw Error('Invalid shape id');const o=create(input.id);return {shapeId:o.userData.shapeId,count:objects.length};}});}catch(e){console.warn('WebMCP registration unavailable',e);}}
historyEnabled=true;window.rippy={catalog,objects,create,select,scene,templates};initGameStudio({objects,scene,camera,renderer,orbit,encode,decode,select,refreshCount,remember,centerPivot,setEditing(value){historyEnabled=value;document.body.classList.toggle('playing',!value);},getSelected:()=>selected});}
start().catch(e=>{console.error(e);$('#loading').hidden=false;$('#loading').textContent='形の読み込みに失敗しました。ページを再読み込みしてください。';});


const sketchDialog=$('#sketch-dialog'),sketchCanvas=$('#sketch-canvas'),sketchContext=sketchCanvas.getContext('2d');let sketchPoints=[],faceClosed=false,sketchBounds={minX:-8,maxX:8,minZ:-4.5,maxZ:4.5};
function drawSketch(){
 const ctx=sketchContext,w=sketchCanvas.width,h=sketchCanvas.height;ctx.clearRect(0,0,w,h);const xs=sketchPoints.map(p=>p[0]),zs=sketchPoints.map(p=>p[1]);let cx=(Math.min(-8,...xs)+Math.max(8,...xs))/2,cz=(Math.min(-4.5,...zs)+Math.max(4.5,...zs))/2;const width=Math.max(16,Math.max(8,...xs)-Math.min(-8,...xs)+2,(Math.max(4.5,...zs)-Math.min(-4.5,...zs)+2)*w/h);sketchBounds={minX:cx-width/2,maxX:cx+width/2,minZ:cz-width*h/w/2,maxZ:cz+width*h/w/2};
 const project=([x,z])=>[(x-sketchBounds.minX)/width*w,(z-sketchBounds.minZ)/(width*h/w)*h];const step=Number($('#snap-step').value);const gridStep=Math.max(step,Math.pow(10,Math.floor(Math.log10(width/40)))) ;
 ctx.lineWidth=1;ctx.strokeStyle='#e1e6ef';for(let x=Math.ceil(sketchBounds.minX/gridStep)*gridStep;x<=sketchBounds.maxX;x+=gridStep){const px=project([x,0])[0];ctx.beginPath();ctx.moveTo(px,0);ctx.lineTo(px,h);ctx.stroke();}for(let z=Math.ceil(sketchBounds.minZ/gridStep)*gridStep;z<=sketchBounds.maxZ;z+=gridStep){const py=project([0,z])[1];ctx.beginPath();ctx.moveTo(0,py);ctx.lineTo(w,py);ctx.stroke();}
 const origin=project([0,0]);ctx.strokeStyle='#dd9aa8';ctx.beginPath();ctx.moveTo(0,origin[1]);ctx.lineTo(w,origin[1]);ctx.stroke();ctx.strokeStyle='#879cda';ctx.beginPath();ctx.moveTo(origin[0],0);ctx.lineTo(origin[0],h);ctx.stroke();ctx.fillStyle='#78839c';ctx.font='13px sans-serif';ctx.fillText('X →',w-42,Math.min(h-8,Math.max(15,origin[1]-8)));ctx.fillText('Z ↓',Math.min(w-38,Math.max(4,origin[0]+8)),h-10);
 if(sketchPoints.length){ctx.beginPath();sketchPoints.forEach((p,i)=>{const [x,y]=project(p);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);});if(faceClosed){ctx.closePath();ctx.fillStyle='#9677ef35';ctx.fill();}ctx.strokeStyle='#8058dc';ctx.lineWidth=2;ctx.stroke();sketchPoints.forEach((p,i)=>{const [x,y]=project(p);ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fillStyle=i===0?'#29a997':'#8058dc';ctx.fill();ctx.fillStyle='#485775';ctx.fillText(String(i+1),x+8,y-8);});}
 $('#sketch-info').textContent=sketchPoints.length+' 点 · '+(faceClosed?'面が閉じています。距離を指定して押し出せます。':'輪郭の順番に点を追加し、最初の点をクリックするか「面を閉じる」を押してください。');$('#extrude').disabled=!faceClosed;$('#close-face').disabled=faceClosed||sketchPoints.length<3;$('#add-point').disabled=faceClosed;$('#undo-point').disabled=!sketchPoints.length;
}
function addSketchPoint(point){if(faceClosed)return;$('#sketch-error').textContent='';if(point.some(v=>!Number.isFinite(v)||Math.abs(v)>10000)){$('#sketch-error').textContent='座標は±10000 m以内の数値にしてください。';return;}if(sketchPoints.length>=200){$('#sketch-error').textContent='点は200個以内にしてください。';return;}if(sketchPoints.some(p=>Math.hypot(p[0]-point[0],p[1]-point[1])<.000001)){$('#sketch-error').textContent='その位置にはすでに点があります。';return;}sketchPoints.push(point);drawSketch();}
function closeFace(){const error=validateFace(sketchPoints);$('#sketch-error').textContent=error??'';if(error)return;faceClosed=true;drawSketch();}
function undoSketchPoint(){if(faceClosed)faceClosed=false;else sketchPoints.pop();$('#sketch-error').textContent='';drawSketch();}
$('#open-sketch').onclick=()=>{if(!historyEnabled)return;sketchDialog.showModal();drawSketch();};$('#close-sketch').onclick=()=>sketchDialog.close();
$('#add-point').onclick=()=>{if($('#point-x').value===''||$('#point-z').value===''){$('#sketch-error').textContent='XとZを入力してください。';return;}addSketchPoint([Number($('#point-x').value),Number($('#point-z').value)]);};
$('#undo-point').onclick=undoSketchPoint;$('#close-face').onclick=closeFace;$('#clear-sketch').onclick=()=>{sketchPoints=[];faceClosed=false;$('#sketch-error').textContent='';drawSketch();};
sketchCanvas.addEventListener('click',e=>{if(faceClosed)return;const rect=sketchCanvas.getBoundingClientRect(),rx=(e.clientX-rect.left)/rect.width,ry=(e.clientY-rect.top)/rect.height;let point=[sketchBounds.minX+rx*(sketchBounds.maxX-sketchBounds.minX),sketchBounds.minZ+ry*(sketchBounds.maxZ-sketchBounds.minZ)];if(sketchPoints.length>=3){const p=sketchPoints[0],dx=(point[0]-p[0])/(sketchBounds.maxX-sketchBounds.minX)*rect.width,dy=(point[1]-p[1])/(sketchBounds.maxZ-sketchBounds.minZ)*rect.height;if(Math.hypot(dx,dy)<12){closeFace();return;}}if($('#snap').checked)point=point.map(snapPosition);addSketchPoint(point);});
sketchDialog.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();undoSketchPoint();}});
$('#extrude').onclick=()=>{try{if(!faceClosed)throw Error('先に面を閉じてください。');const distance=Number($('#extrude-distance').value),geometry=makeExtrusion(sketchPoints,distance);remember();const o=new T.Mesh(geometry,new T.MeshStandardMaterial({color:'#9c88ec',roughness:.62,metalness:.03}));o.userData={label:'押し出し '+distance+' m',sketch:{points:structuredClone(sketchPoints),distance}};o.castShadow=true;o.receiveShadow=true;scene.add(o);objects.push(o);select(o);refreshCount();sketchDialog.close();$('#focus').click();$('#status').textContent='描いた面を '+distance+' m 押し出しました';sketchPoints=[];faceClosed=false;}catch(e){$('#sketch-error').textContent=e.message;}};



const sweepDialog=$('#sweep-dialog'),sweepCanvas=$('#sweep-canvas'),sweepCtx=sweepCanvas.getContext('2d');let sweepCustom=null,sweepView={minX:-3,minZ:-3,width:12,height:12*320/720};
function readSweepPath(){const text=$('#sweep-path').value.trim();if(!text)return [];return text.split(/\n/).filter(l=>l.trim()).map(line=>{const values=line.trim().split(/[ ,、\t]+/).map(Number);if(values.length!==3||values.some(n=>!Number.isFinite(n)||Math.abs(n)>10000))throw Error('各行に X, Y, Z を数値で入力してください（±10000 m以内）。');return values;});}
function writeSweepPath(points){$('#sweep-path').value=points.map(p=>p.join(', ')).join('\n');drawSweepPath();}
function drawSweepPath(){const ctx=sweepCtx,w=sweepCanvas.width,h=sweepCanvas.height;ctx.clearRect(0,0,w,h);let path;try{path=readSweepPath();$('#sweep-error').textContent='';}catch(e){$('#sweep-error').textContent=e.message;return;}const xs=path.map(p=>p[0]),zs=path.map(p=>p[2]),minX=Math.min(-2,...xs)-1,maxX=Math.max(6,...xs)+1,minZ=Math.min(-2,...zs)-1,maxZ=Math.max(6,...zs)+1,width=Math.max(maxX-minX,(maxZ-minZ)*w/h),height=width*h/w;sweepView={minX:(minX+maxX-width)/2,minZ:(minZ+maxZ-height)/2,width,height};const project=p=>[(p[0]-sweepView.minX)/width*w,(p[2]-sweepView.minZ)/height*h];const step=Math.max(1,Math.pow(10,Math.floor(Math.log10(width/25))));ctx.strokeStyle='#dfe4ee';ctx.lineWidth=1;for(let x=Math.ceil(sweepView.minX/step)*step;x<sweepView.minX+width;x+=step){const p=project([x,0,0]);ctx.beginPath();ctx.moveTo(p[0],0);ctx.lineTo(p[0],h);ctx.stroke();}for(let z=Math.ceil(sweepView.minZ/step)*step;z<sweepView.minZ+height;z+=step){const p=project([0,0,z]);ctx.beginPath();ctx.moveTo(0,p[1]);ctx.lineTo(w,p[1]);ctx.stroke();}ctx.fillStyle='#7a829b';ctx.font='12px sans-serif';ctx.fillText('上面図 · X → / Z ↓',10,20);if(path.length){let display=path;if(path.length>2&&$('#sweep-smooth').checked){const curve=new T.CatmullRomCurve3(path.map(p=>new T.Vector3(...p)),false,'centripetal');display=curve.getPoints(120).map(p=>p.toArray());}ctx.beginPath();display.forEach((p,i)=>{const [x,y]=project(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.strokeStyle='#8058dc';ctx.lineWidth=3;ctx.stroke();path.forEach((p,i)=>{const [x,y]=project(p);ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fillStyle=i===0?'#29a997':'#8058dc';ctx.fill();ctx.fillStyle='#485775';ctx.fillText((i+1)+' · Y='+p[1],x+8,y-8);});}}
function updateSweepProfile(){const custom=$('#sweep-profile').value==='custom';$('#sweep-profile-info').textContent=custom?(sweepCustom?'描いた面を断面に使います。幅に合わせて中心をそろえます。':'「面を描く・押し出す」で面を閉じて「この断面でスイープ」を押すか、押し出した形を選択してください。'):$('#sweep-profile').value==='circle'?'円の断面を伸ばします。':'四角い断面を伸ばします。';}
function openSweep(custom){if(custom){sweepCustom=structuredClone(custom);$('#sweep-profile').value='custom';}updateSweepProfile();sweepDialog.showModal();drawSweepPath();}
$('#open-sweep').onclick=()=>{if(!historyEnabled)return;openSweep(selected?.userData.sketch?.points??null);};$('#close-sweep').onclick=()=>sweepDialog.close();
$('#sweep-sketch').onclick=()=>{const error=validateFace(sketchPoints);if(!faceClosed||error){$('#sketch-error').textContent=error??'先に面を閉じてください。';return;}sketchDialog.close();openSweep(sketchPoints);};
$('#sweep-profile').onchange=updateSweepProfile;$('#sweep-path').oninput=drawSweepPath;$('#sweep-smooth').onchange=drawSweepPath;
function appendSweepPoint(point){try{const points=readSweepPath();if(points.length>=100)throw Error('経路は100点以内にしてください。');if(point.some(v=>!Number.isFinite(v)||Math.abs(v)>10000))throw Error('座標は±10000 m以内の数値にしてください。');if(points.length&&new T.Vector3(...points.at(-1)).distanceTo(new T.Vector3(...point))<.001)throw Error('同じ位置に連続して点を置けません。');writeSweepPath([...points,point]);}catch(e){$('#sweep-error').textContent=e.message;}}
$('#sweep-add').onclick=()=>{const fields=['x','y','z'].map(a=>$('#sweep-'+a));if(fields.some(f=>f.value==='')){$('#sweep-error').textContent='X・Y・Zを入力してください。';return;}appendSweepPoint(fields.map(f=>Number(f.value)));};
$('#sweep-back').onclick=()=>{try{writeSweepPath(readSweepPath().slice(0,-1));}catch(e){$('#sweep-error').textContent=e.message;}};$('#sweep-clear').onclick=()=>writeSweepPath([]);
sweepCanvas.onclick=e=>{const r=sweepCanvas.getBoundingClientRect();const x=sweepView.minX+(e.clientX-r.left)/r.width*sweepView.width,z=sweepView.minZ+(e.clientY-r.top)/r.height*sweepView.height;if($('#sweep-y').value===''){$('#sweep-error').textContent='高さYを入力してください。';return;}appendSweepPoint([snapPosition(x),Number($('#sweep-y').value),snapPosition(z)]);};
$('#sweep-create').onclick=()=>{try{const size=Number($('#sweep-size').value);if(!Number.isFinite(size)||size<.01||size>100)throw Error('断面の幅は0.01〜100 mにしてください。');let profile;const type=$('#sweep-profile').value;if(type==='circle')profile=Array.from({length:32},(_,i)=>[Math.cos(i/32*Math.PI*2)*size/2,Math.sin(i/32*Math.PI*2)*size/2]);else if(type==='square')profile=[[-size/2,-size/2],[size/2,-size/2],[size/2,size/2],[-size/2,size/2]];else{if(!sweepCustom)throw Error('先に断面を描いてください。');const xs=sweepCustom.map(p=>p[0]),ys=sweepCustom.map(p=>p[1]),cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2,extent=Math.max(Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys));profile=sweepCustom.map(([x,y])=>[(x-cx)*size/extent,(y-cy)*size/extent]);}const data={profile,path:readSweepPath(),smooth:$('#sweep-smooth').checked};const geometry=makeSweep(data);remember();const mesh=new T.Mesh(geometry,new T.MeshStandardMaterial({color:'#9c88ec',roughness:.62,metalness:.03}));mesh.userData={label:'スイープ',sweep:structuredClone(data)};mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);objects.push(mesh);select(mesh);refreshCount();sweepDialog.close();$('#focus').click();$('#status').textContent='断面を経路に沿ってスイープしました';}catch(e){$('#sweep-error').textContent=e.message;}};


const revolveDialog=$('#revolve-dialog'),revolveCanvas=$('#revolve-canvas'),revolveCtx=revolveCanvas.getContext('2d');let revolveView={radius:4,minY:-2,maxY:4};
function readRevolve(){const value=$('#revolve-profile').value.trim();if(!value)return [];const points=value.split('\n').filter(l=>l.trim()).map(l=>{const pair=l.trim().split(/[ ,、\t]+/).map(Number);if(pair.length!==2||pair.some(n=>!Number.isFinite(n)||Math.abs(n)>10000)||pair[0]<0)throw Error('半径は0以上、座標は±10000以内の数値で指定してください。');return pair;});if(points.length>200)throw Error('断面は200点以内で描いてください。');return points;}
function writeRevolve(points){$('#revolve-profile').value=points.map(p=>p.join(', ')).join('\n');drawRevolve();}
function drawRevolve(){let points;try{points=readRevolve();$('#revolve-error').textContent='';}catch(e){$('#revolve-error').textContent=e.message;return;}const w=revolveCanvas.width,h=revolveCanvas.height,ctx=revolveCtx;ctx.clearRect(0,0,w,h);const minY=Math.min(-1,...points.map(p=>p[1]))-.5,maxY=Math.max(2,...points.map(p=>p[1]))+.5,scale=Math.min((w-80)/Math.max(4,...points.map(p=>p[0]+.5)),(h-40)/(maxY-minY));revolveView={scale,minY,maxY};const project=([r,y])=>[40+r*scale,h-20-(y-minY)*scale];ctx.strokeStyle='#dfe4ee';ctx.lineWidth=1;const step=Math.max(.5,Math.pow(10,Math.floor(Math.log10(Math.max(maxY-minY,4)/20))));for(let r=0;r<(w-40)/scale;r+=step){const x=project([r,0])[0];ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=Math.ceil(minY/step)*step;y<maxY;y+=step){const py=project([0,y])[1];ctx.beginPath();ctx.moveTo(0,py);ctx.lineTo(w,py);ctx.stroke();}ctx.strokeStyle='#3aa389';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(40,10);ctx.lineTo(40,h-10);ctx.stroke();ctx.font='13px sans-serif';ctx.fillStyle='#338875';ctx.fillText('回転軸 Y',48,18);ctx.fillStyle='#8991a4';ctx.fillText('半径 →',w-65,h-8);if(points.length){ctx.beginPath();points.forEach((p,i)=>{const [x,y]=project(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});if(points.length>=3){ctx.closePath();ctx.fillStyle='#9677ef30';ctx.fill();}ctx.strokeStyle='#8058dc';ctx.lineWidth=2;ctx.stroke();for(const p of points){const [x,y]=project(p);ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle='#8058dc';ctx.fill();}}}
function sphereProfile(){writeRevolve(Array.from({length:33},(_,i)=>{const t=-Math.PI/2+i/32*Math.PI;return [Number(Math.max(0,Math.cos(t)).toFixed(6)),Number((Math.sin(t)+1).toFixed(6))];}));}
$('#open-revolve').onclick=()=>{if(!historyEnabled)return;if(!$('#revolve-profile').value)sphereProfile();revolveDialog.showModal();drawRevolve();};$('#close-revolve').onclick=()=>revolveDialog.close();$('#revolve-sphere').onclick=sphereProfile;$('#revolve-vase').onclick=()=>writeRevolve([[0,0],[.8,0],[1,.5],[.9,1.2],[.4,1.8],[.5,2.2],[.35,2.2],[.25,1.8],[.7,1.2],[.8,.5],[.65,.2],[0,.2]]);$('#revolve-clear').onclick=()=>writeRevolve([]);$('#revolve-back').onclick=()=>{try{writeRevolve(readRevolve().slice(0,-1));}catch(e){$('#revolve-error').textContent=e.message;}};$('#revolve-profile').oninput=drawRevolve;
revolveCanvas.onclick=e=>{try{const rect=revolveCanvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*revolveCanvas.width,y=(e.clientY-rect.top)/rect.height*revolveCanvas.height;const r=(x-40)/revolveView.scale,height=revolveView.minY+(revolveCanvas.height-20-y)/revolveView.scale;if(r<-.05)throw Error('回転軸の右側に点を置いてください。');const point=[Math.max(0,snapPosition(r)),snapPosition(height)],points=readRevolve();if(points.length>=200)throw Error('断面は200点以内にしてください。');writeRevolve([...points,point]);}catch(e){$('#revolve-error').textContent=e.message;}};
$('#revolve-sketch').onclick=()=>{const error=validateFace(sketchPoints);if(!faceClosed||error){$('#sketch-error').textContent=error??'先に面を閉じてください。';return;}if(sketchPoints.some(p=>p[0]<0)){$('#sketch-error').textContent='回転体の断面はX=0の軸の右側に描いてください。';return;}sketchDialog.close();writeRevolve(sketchPoints);revolveDialog.showModal();drawRevolve();};
$('#revolve-create').onclick=()=>{try{const data={profile:readRevolve(),angle:Number($('#revolve-angle').value)},geometry=makeRevolve(data);remember();const o=new T.Mesh(geometry,new T.MeshStandardMaterial({color:'#9c88ec',roughness:.62,metalness:.03}));o.userData={label:'回転体 '+data.angle+'°',revolve:structuredClone(data)};o.castShadow=true;o.receiveShadow=true;scene.add(o);objects.push(o);centerPivot(o);select(o);refreshCount();revolveDialog.close();$('#focus').click();$('#status').textContent='断面を '+data.angle+'° 回して立体にしました';}catch(e){$('#revolve-error').textContent=e.message;}};

