import * as T from 'three';
export function createGameInput(canvas,objects,camera,emit,onStop){
 let active=false,keys=new Set(),buttons=new Set(),pointer={inside:false,target:0,x:0,y:0,dx:0,dy:0},client=null,down=null,lastDrag=false;
 const ray=new T.Raycaster(),plane=new T.Plane(new T.Vector3(0,1,0),0);
 const isUI=e=>e.target?.closest?.('[data-game-ui]');
 function hit(x,y){const r=canvas.getBoundingClientRect(),inside=x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;if(!inside)return{inside:false,target:0,x:x-r.left,y:y-r.top};camera.updateMatrixWorld();objects.forEach(o=>o.updateWorldMatrix(true,true));ray.setFromCamera(new T.Vector2((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2),camera);const contact=ray.intersectObjects(objects.filter(o=>o.visible),true)[0];let target=0;if(contact){let object=contact.object;while(object.parent&&!objects.includes(object))object=object.parent;target=objects.indexOf(object)+1;}const point=contact?.point??ray.ray.intersectPlane(plane,new T.Vector3());return{inside,target,x:x-r.left,y:y-r.top,worldX:point?.x??0,worldY:point?.y??0,worldZ:point?.z??0};}
 const send=(kind,extra={})=>{emit({type:'pointer',kind,...pointer,...extra});if(kind==='mouseover'||kind==='mouseout')emit({type:'pointer',kind:kind==='mouseover'?'mouseenter':'mouseleave',...pointer,...extra});};
 function refresh(){if(!client)return;const next=hit(...client);if(next.target!==pointer.target||next.inside!==pointer.inside){if(pointer.inside)send('mouseout',{target:pointer.target});const old=pointer;pointer={...pointer,...next};if(next.inside)send('mouseover',{target:next.target,dx:next.x-old.x,dy:next.y-old.y});}else pointer={...pointer,...next};}
 window.addEventListener('keydown',e=>{if(!active)return;if(e.key==='Escape'){e.preventDefault();onStop();return;}if(isUI(e)||e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase();if(!keys.has(key))emit({type:'key',key});keys.add(key);if(e.key.length===1)emit({type:'keypress',key});if(!isUI(e))e.preventDefault();},true);
 window.addEventListener('keyup',e=>{if(!active)return;const key=e.key.toLowerCase();if(keys.delete(key))emit({type:'keyup',key});});
 window.addEventListener('blur',()=>{if(!active)return;for(const key of keys)emit({type:'keyup',key});keys.clear();buttons.clear();down=null;});
 canvas.addEventListener('pointerdown',e=>{if(!active)return;e.preventDefault();canvas.focus();client=[e.clientX,e.clientY];refresh();buttons.add(e.button);down={x:e.clientX,y:e.clientY,target:pointer.target,button:e.button,dragging:false};lastDrag=false;send('mousedown',{button:e.button});if(e.pointerType==='touch')send('touchstart',{button:e.button});});
 window.addEventListener('pointermove',e=>{if(!active)return;if(isUI(e)){if(pointer.inside)send('mouseout');pointer.inside=false;pointer.target=0;client=null;return;}const r=canvas.getBoundingClientRect();if(!down&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)){if(pointer.inside){send('mouseout');pointer.inside=false;pointer.target=0;}client=null;return;}const old={...pointer};client=[e.clientX,e.clientY];refresh();pointer.dx=pointer.x-old.x;pointer.dy=pointer.y-old.y;if(pointer.inside)send('mousemove',{button:e.button});if(e.pointerType==='touch'&&down)send('touchmove',{button:down.button});if(down){if(!down.dragging&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>4){down.dragging=true;send('dragstart',{target:down.target,button:down.button});}if(down.dragging)send('drag',{target:down.target,other:pointer.target,button:down.button});}});
 window.addEventListener('pointerup',e=>{if(!active||!down)return;client=[e.clientX,e.clientY];refresh();send('mouseup',{button:e.button});if(e.pointerType==='touch')send('touchend',{button:e.button});if(down.dragging)send('dragend',{target:down.target,other:pointer.target,button:down.button});lastDrag=down.dragging;down=null;buttons.delete(e.button);});
 window.addEventListener('pointercancel',()=>{buttons.clear();down=null;});
 canvas.addEventListener('click',e=>{if(active&&!lastDrag){client=[e.clientX,e.clientY];refresh();send('click',{button:e.button});}});
 canvas.addEventListener('dblclick',e=>{if(active&&!lastDrag)send('dblclick',{button:e.button});});
 canvas.addEventListener('wheel',e=>{if(active){e.preventDefault();client=[e.clientX,e.clientY];refresh();send('wheel',{wheel:e.deltaY,button:0});}},{passive:false});
 canvas.addEventListener('contextmenu',e=>{if(active)e.preventDefault();});
 const api={start(){active=true;keys.clear();buttons.clear();pointer={inside:false,target:0,x:0,y:0,dx:0,dy:0};client=null;down=null;canvas.tabIndex=0;canvas.focus();},stop(){active=false;keys.clear();buttons.clear();down=null;},snapshot(){refresh();return{keys:[...keys],pointer:{...pointer,buttons:[...buttons]}};}};return api;
}
