import {collisionDelta} from './game-collision.js';
import * as T from 'three';
import {TYPES} from './graph-schema.js';
export function createGameCamera(canvas,objects,camera,orbit){
 let active=false,config,drag=null,frame=0,yaw=0,pitch=.25,distance=6,saved,hiddenLayers=[];
 const forwardAxis={'-z':new T.Vector3(0,0,-1),'+z':new T.Vector3(0,0,1),'+x':new T.Vector3(1,0,0),'-x':new T.Vector3(-1,0,0)};
 const forward=()=>new T.Vector3(Math.sin(yaw),0,-Math.cos(yaw));
 function update(){if(!active)return;const player=objects[config.player-1],aim=player?player.position.clone().add(new T.Vector3(0,config.view==='first'?config.eyeHeight:config.height,0)):saved.target.clone();const direction=new T.Vector3(Math.sin(yaw)*Math.cos(pitch),-Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch));
 if(player&&config.view==='first'){camera.position.copy(aim);orbit.target.copy(aim).add(direction);}
 else{camera.position.copy(aim).addScaledVector(direction,-distance);orbit.target.copy(aim);}
 camera.lookAt(orbit.target);camera.updateMatrixWorld();
 }
 function animate(){if(!active)return;update();frame=requestAnimationFrame(animate);}
 canvas.addEventListener('pointerdown',e=>{if(!active||e.button!==2)return;e.preventDefault();drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);});
 window.addEventListener('pointermove',e=>{if(!active||!drag||drag.id!==e.pointerId)return;yaw-=(e.clientX-drag.x)*.005*config.sensitivity;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-drag.y)*.005*config.sensitivity));drag.x=e.clientX;drag.y=e.clientY;update();});
 const release=()=>{drag=null;};window.addEventListener('pointerup',release);window.addEventListener('pointercancel',release);window.addEventListener('blur',release);
 canvas.addEventListener('wheel',e=>{if(!active)return;e.preventDefault();const factor=Math.exp(Math.max(-100,Math.min(100,e.deltaY))*.002);if(config.player&&config.view==='first'){camera.fov=Math.max(25,Math.min(100,camera.fov*factor));camera.updateProjectionMatrix();}else distance=Math.max(.3,Math.min(500,distance*factor));update();},{passive:false});
 return{
 start(graph){config={...TYPES.setup.defaults,...graph.nodes.find(n=>n.type==='setup')?.params};saved={position:camera.position.clone(),quaternion:camera.quaternion.clone(),target:orbit.target.clone(),fov:camera.fov,near:camera.near,layers:camera.layers.mask};active=true;const player=objects[config.player-1];if(player){if(config.view==='first'){hiddenLayers=[];player.traverse(o=>{if(o.isMesh){hiddenLayers.push([o,o.layers.mask]);o.layers.set(31);}});camera.layers.disable(31);}const front=forwardAxis[config.forward].clone().applyQuaternion(player.quaternion);yaw=Math.atan2(front.x,-front.z)+(config.view==='front'?Math.PI:0);pitch=config.view==='first'?0:.25;distance=config.distance;camera.near=Math.min(camera.near,.03);camera.updateProjectionMatrix();}else{const d=orbit.target.clone().sub(camera.position);distance=Math.max(.3,d.length());d.normalize();yaw=Math.atan2(d.x,-d.z);pitch=-Math.asin(Math.max(-1,Math.min(1,d.y)));}animate();},
 move(keys,dt){if(!active||config.controls==='none')return;const set=new Set(keys),wasd=['both','wasd'].includes(config.controls),arrows=['both','arrows'].includes(config.controls);const z=Number(wasd&&set.has('w')||arrows&&set.has('arrowup'))-Number(wasd&&set.has('s')||arrows&&set.has('arrowdown')),x=Number(wasd&&set.has('d')||arrows&&set.has('arrowright'))-Number(wasd&&set.has('a')||arrows&&set.has('arrowleft'));if(!x&&!z)return;const direction=forward().multiplyScalar(z).add(new T.Vector3(Math.cos(yaw),0,Math.sin(yaw)).multiplyScalar(x)).normalize();const delta=direction.clone().multiplyScalar(config.speed*Math.max(0,Math.min(.1,dt)));const ids=new Set([config.player,...config.movers]);for(const id of ids){const o=objects[id-1];if(o){const world=objects.map(obj=>{obj.updateWorldMatrix(true,true);const box=new T.Box3().setFromObject(obj);return{visible:obj.visible,min:box.min.toArray(),max:box.max.toArray()};});o.position.add(new T.Vector3(...(config.collision?collisionDelta(world,id-1,delta.toArray()):delta.toArray())));}}const player=objects[config.player-1];if(player&&config.turn){const axis=forwardAxis[config.forward];const old=player.rotation.clone();player.rotation.set(0,Math.atan2(axis.x,-axis.z)-Math.atan2(direction.x,-direction.z),0);if(config.collision){player.updateWorldMatrix(true,true);const a=new T.Box3().setFromObject(player);const overlaps=objects.some(o=>{if(o===player||!o.visible)return false;o.updateWorldMatrix(true,true);const b=new T.Box3().setFromObject(o);return ['x','y','z'].every(k=>a.max[k]>b.min[k]+1e-7&&a.min[k]<b.max[k]-1e-7);});if(overlaps)player.rotation.copy(old);}}update();},
 stop(){if(!active)return;active=false;cancelAnimationFrame(frame);drag=null;camera.position.copy(saved.position);camera.quaternion.copy(saved.quaternion);camera.fov=saved.fov;camera.near=saved.near;camera.layers.mask=saved.layers;for(const [o,mask]of hiddenLayers)o.layers.mask=mask;hiddenLayers=[];camera.updateProjectionMatrix();orbit.target.copy(saved.target);},
 update
 };
}
