import {placeUI} from './ui-layout.js?v=20260926-studio1';
import {UI_EVENTS} from './graph-schema.js?v=20260926-studio1';
export function createGameUI(viewport,emit){
 const layer=document.createElement('div');layer.id='game-ui';layer.hidden=true;viewport.append(layer);const controls=new Map(),prompts=new Map(),layouts=new Map();const flow=document.createElement('div');flow.className='game-ui-flow';layer.append(flow);
 const notify=(kind,id,e,control)=>{const r=viewport.getBoundingClientRect();emit({type:'ui_event',kind,ui:id,value:control.type==='checkbox'?control.checked:control.type==='range'||control.type==='number'?Number(control.value):control.value??control.textContent,key:e.key?.toLowerCase(),x:(e.clientX??r.left)-r.left,y:(e.clientY??r.top)-r.top,button:e.button??0,wheel:e.deltaY??0});};
 function create(id,kind,text,value,options){if(!controls.has(id)&&controls.size>=50)throw Error('画面UIは50個までです');controls.get(id)?.wrapper.remove();const wrapper=document.createElement('div');wrapper.className='game-control';wrapper.dataset.gameUi=id;let control;
 if(kind==='form'){wrapper.innerHTML='<form><label></label><input aria-label="回答"><button type="submit">送信</button></form>';control=wrapper.querySelector('input');wrapper.querySelector('label').textContent=text;control.value=String(value);wrapper.querySelector('form').onsubmit=e=>{e.preventDefault();notify('submit',id,e,control);};}
 else{control=document.createElement(kind==='button'?'button':kind==='select'?'select':kind==='label'?'span':kind==='textarea'?'textarea':'input');if(['text','number','checkbox','slider'].includes(kind))control.type=kind==='slider'?'range':kind;if(kind==='slider'){control.min=0;control.max=100;}if(kind==='select')for(const item of options.split(',')){const option=document.createElement('option');option.textContent=item;option.value=item;control.append(option);}if(kind==='button'||kind==='label')control.textContent=text;else{const label=document.createElement('label');label.textContent=text;wrapper.append(label);control.setAttribute('aria-label',text||id);if(kind==='checkbox')control.checked=Boolean(value);else control.value=String(value);}wrapper.append(control);}
 for(const [,kind]of UI_EVENTS){if(['submit','touchstart','touchmove','touchend'].includes(kind))continue;control.addEventListener(kind,e=>notify(kind,id,e,control));}for(const [pointer,touch]of [['pointerdown','touchstart'],['pointermove','touchmove'],['pointerup','touchend']])control.addEventListener(pointer,e=>{if(e.pointerType==='touch')notify(touch,id,e,control);});
 controls.set(id,{wrapper,control,kind});const layout=layouts.get(id);if(layout){placeUI(wrapper,layout);wrapper.classList.add('placed-ui');layer.append(wrapper);}else flow.append(wrapper);layer.hidden=false;
 }
 return{clear(){controls.clear();prompts.clear();layouts.clear();flow.replaceChildren();layer.replaceChildren(flow);layer.hidden=true;},mount(items){this.clear();for(const item of items){layouts.set(item.id,item);create(item.id,item.kind,item.text,item.kind==='checkbox'?item.value==='true':item.value,item.options);}},apply(type,args){
 if(type==='ui_create'){create(...args);return true;}
 if(type==='ui_set'){const [id,property,value]=args,entry=controls.get(id);if(!entry)throw Error('UI「'+id+'」はまだ作られていません');const{control,wrapper,kind}=entry;if(property==='visible')wrapper.hidden=!Boolean(value);if(property==='enabled')control.disabled=!Boolean(value);if(property==='value'){if(control.type==='checkbox')control.checked=Boolean(value);else control.value=String(value);}if(property==='text'){if(['button','label'].includes(kind))control.textContent=String(value);else wrapper.querySelector('label').textContent=String(value);}return true;}
 if(type==='prompt'){const [token,name,text]=args,form=document.createElement('form');form.className='game-question';form.dataset.gameUi='question-'+token;const label=document.createElement('label');label.textContent=text;const input=document.createElement('input');input.setAttribute('aria-label',text||'回答');input.maxLength=500;const button=document.createElement('button');button.textContent='回答する';form.append(label,input,button);form.onsubmit=e=>{e.preventDefault();emit({type:'answer',token,name,value:input.value});prompts.delete(token);form.remove();};prompts.set(token,form);flow.append(form);layer.hidden=false;return true;}return false;
 }};
}
