import {Blockly as B,javascriptGenerator as G} from './vendor/blocks.js';
export function createBlocks(container,getObjects){
 const target=()=>new B.FieldDropdown(()=>getObjects().length?getObjects().map((o,i)=>[(i+1)+'：'+o.userData.label,String(i+1)]):[['形なし','1']]);
 const number=n=>new B.FieldNumber(n,-100000,100000);
 for(const [type,label]of [['start','開始したとき'],['tick','毎フレーム（dt 秒）'],['key','キーを押したとき']]){
 B.Blocks['game_'+type]={init(){const row=this.appendDummyInput().appendField(label);if(type==='key')row.appendField(new B.FieldTextInput('ArrowRight'),'KEY');this.appendStatementInput('DO');this.setColour(45);}};
 G.forBlock['game_'+type]=(b,g)=>{const body=g.statementToCode(b,'DO');return type==='key'?`on_key(${JSON.stringify(b.getFieldValue('KEY'))}, () => {\n${body}});\n`:`on_${type}(${type==='tick'?'dt':''} => {\n${body}});\n`.replace('on_start( =>','on_start(() =>');};
 }
 for(const [type,label]of [['move','移動'],['rotate','回転（度）'],['set_position','位置を設定']]){
 B.Blocks['game_'+type]={init(){this.appendDummyInput().appendField('形').appendField(target(),'ID').appendField(label);const row=this.appendDummyInput();for(const a of ['X','Y','Z'])row.appendField(a).appendField(number(a==='X'&&type==='move'?1:0),a);this.setPreviousStatement(true);this.setNextStatement(true);this.setColour(230);}};
 G.forBlock['game_'+type]=b=>`${type}(${b.getFieldValue('ID')}, ${['X','Y','Z'].map(a=>b.getFieldValue(a)).join(', ')});\n`;
 }
 for(const [type,label]of [['hide','隠す'],['show','表示する']]){B.Blocks['game_'+type]={init(){this.appendDummyInput().appendField('形').appendField(target(),'ID').appendField(label);this.setPreviousStatement(true);this.setNextStatement(true);this.setColour(230);}};G.forBlock['game_'+type]=b=>`${type}(${b.getFieldValue('ID')});\n`;}
 B.Blocks.game_score={init(){this.appendDummyInput().appendField('得点を').appendField(number(1),'N').appendField('増やす');this.setPreviousStatement(true);this.setNextStatement(true);this.setColour(160);}};G.forBlock.game_score=b=>`add_score(${b.getFieldValue('N')});\n`;
 B.Blocks.game_say={init(){this.appendDummyInput().appendField('メッセージ').appendField(new B.FieldTextInput('ゲームスタート！'),'TEXT');this.setPreviousStatement(true);this.setNextStatement(true);this.setColour(160);}};G.forBlock.game_say=b=>`say(${JSON.stringify(b.getFieldValue('TEXT'))});\n`;
 B.Blocks.game_touching={init(){this.appendDummyInput().appendField('形').appendField(target(),'A').appendField('と').appendField(target(),'B').appendField('が重なる');this.setOutput(true,'Boolean');this.setColour(200);}};G.forBlock.game_touching=b=>[`touching(${b.getFieldValue('A')}, ${b.getFieldValue('B')})`,G.ORDER_FUNCTION_CALL];
 B.Blocks.game_keydown={init(){this.appendDummyInput().appendField('キー').appendField(new B.FieldTextInput('ArrowRight'),'KEY').appendField('を押している');this.setOutput(true,'Boolean');this.setColour(200);}};G.forBlock.game_keydown=b=>[`key_down(${JSON.stringify(b.getFieldValue('KEY'))})`,G.ORDER_FUNCTION_CALL];
 B.Blocks.game_color={init(){this.appendDummyInput().appendField('形').appendField(target(),'ID').appendField('の色を').appendField(new B.FieldDropdown([['赤','#ff5555'],['青','#4488ff'],['緑','#44cc88'],['黄','#ffcc33'],['紫','#9966ee'],['白','#ffffff'],['黒','#222222']]),'COLOR').appendField('にする');this.setPreviousStatement(true);this.setNextStatement(true);this.setColour(230);}};G.forBlock.game_color=b=>'set_color('+b.getFieldValue('ID')+', '+JSON.stringify(b.getFieldValue('COLOR'))+');\n';
 const category=(name,colour,types)=>({kind:'category',name,colour,contents:types.map(type=>({kind:'block',type}))});
 const workspace=B.inject(container,{media:'./vendor/blockly-media/',trashcan:true,scrollbars:true,zoom:{controls:true,wheel:true,startScale:.9},toolbox:{kind:'categoryToolbox',contents:[category('イベント',45,['game_start','game_key','game_tick']),category('形を動かす',230,['game_move','game_rotate','game_set_position','game_hide','game_show','game_color']),category('ゲーム',160,['game_score','game_say','game_touching','game_keydown']),category('条件・繰り返し',210,['controls_if','controls_repeat_ext','logic_compare','logic_boolean','math_number'])]}});
 return {workspace,resize:()=>B.svgResize(workspace),save:()=>B.serialization.workspaces.save(workspace),load:state=>B.serialization.workspaces.load(state,workspace),code:()=>G.workspaceToCode(workspace),example(id){workspace.clear();const key=workspace.newBlock('game_key');key.setFieldValue('ArrowRight','KEY');const move=workspace.newBlock('game_move');move.setFieldValue(String(id),'ID');const score=workspace.newBlock('game_score');key.getInput('DO').connection.connect(move.previousConnection);move.nextConnection.connect(score.previousConnection);for(const b of workspace.getAllBlocks(false)){b.initSvg();b.render();}key.moveBy(35,35);}};
}
