import {captureKit,validateKit,mergeKit,makeGameTemplate,GAME_TEMPLATES} from './game-kits.js?v=20260926-studio1';
export function createGameLibrary({capture,apply,getSelectedIds,beforeOpen}){
 const dialog=document.createElement('dialog');dialog.id='game-library';dialog.innerHTML='<h2>部品セット・ゲームのひな形</h2><button data-close>閉じる</button><section><h3>ゲームのひな形</h3><select aria-label="ゲームのひな形"></select><button data-template>このひな形で始める</button><p>現在のゲームを置き換えます。「置き換え前に戻す」で戻せます。</p><button data-restore disabled>置き換え前に戻す</button></section><section><h3>部品とノードを登録</h3><input aria-label="部品セットの名前" placeholder="開くドア、動く床など" maxlength="40"><label><input type="checkbox" data-selected checked>選択した形と関連ノードだけ（参照する形も含む）</label><button data-register>登録する</button><button data-import>ファイルから登録</button><input type="file" accept=".json" data-file hidden><p>このブラウザーに保存します。ファイルに書き出すと別の環境にも持ち運べます。</p><div data-kits></div></section><p role="status" data-status></p>';
 document.body.append(dialog);const $=s=>dialog.querySelector(s),status=text=>$('[data-status]').textContent=text;let previous=null,kits=[];
 try{kits=JSON.parse(localStorage.getItem('rippy-kits-v1')??'[]');if(!Array.isArray(kits))kits=[];}catch{kits=[];}
 const persist=next=>{localStorage.setItem('rippy-kits-v1',JSON.stringify(next));kits=next;};
 const attempt=fn=>{try{fn();}catch(e){status(e.message);}};
 function render(){const list=$('[data-kits]');list.replaceChildren();for(const [index,entry]of kits.entries()){const row=document.createElement('div');const name=document.createElement('b');name.textContent=entry.name;row.append(name);const add=document.createElement('button');add.textContent='ゲームに置く';add.onclick=()=>attempt(()=>{const current=capture(),next=mergeKit(current,entry.data,'k'+Date.now().toString(36)+'_');apply(next);previous=current;$('[data-restore]').disabled=false;status('部品とノードを追加しました。');});const save=document.createElement('button');save.textContent='ファイルに保存';save.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(entry)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='rippy-kit.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};const remove=document.createElement('button');remove.textContent='登録を削除';remove.onclick=()=>attempt(()=>{persist(kits.filter((_,i)=>i!==index));render();status('登録を削除しました。配置済みの部品は残っています。');});row.append(add,save,remove);list.append(row);}}
 for(const [value,label]of Object.entries(GAME_TEMPLATES)){const option=document.createElement('option');option.value=value;option.textContent=label;$('select').append(option);}
 $('[data-close]').onclick=()=>dialog.close();$('[data-template]').onclick=()=>attempt(()=>{const next=makeGameTemplate($('select').value),current=capture();apply(next);previous=current;$('[data-restore]').disabled=false;status('ひな形を作成しました。閉じてプレイで試せます。');});
 $('[data-restore]').onclick=()=>attempt(()=>{if(!previous)return;apply(previous);previous=null;$('[data-restore]').disabled=true;status('元のゲームに戻しました。');});
 $('[data-register]').onclick=()=>attempt(()=>{const name=$('[aria-label="部品セットの名前"]').value.trim();if(!name)throw Error('部品セットの名前を入力してください');const selected=$('[data-selected]').checked?getSelectedIds():null;if(selected&&!selected.length)throw Error('保存する形を先に選んでください');const data=validateKit(captureKit(capture(),selected));persist([...kits,{name,data}]);render();status('登録しました。別のゲームでも「ゲームに置く」で使えます。');});
 $('[data-import]').onclick=()=>$('[data-file]').click();$('[data-file]').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>30000000)throw Error('30MB以下のファイルを選んでください');const entry=JSON.parse(await file.text());if(typeof entry.name!=='string'||entry.name.length>40)throw Error('部品セットの名前が不正です');entry.data=validateKit(entry.data);persist([...kits,entry]);render();status('部品セットを登録しました。');}catch(error){status(error.message);}e.target.value='';};
 return {open(){beforeOpen();render();dialog.showModal();}};
}
