import {TYPES,KEYS,outputs,validateGraph} from './graph-core.js';
export function createGraphEditor(host,getObjects,notice){
 let graph={nodes:[],edges:[]},selected=null,pending=null,serial=0,zoom=1;const history=[],redo=[];
 host.innerHTML='<aside class="node-palette"><h3>ノードを追加</h3><input id="node-search" aria-label="ノードを検索" placeholder="ノードを検索"><div id="node-types"></div><p>出力の ○ → 入力の ○ をクリック、またはドラッグで接続。線をクリックして切断。</p></aside><section class="graph-area"><div class="graph-tools"><button id="graph-undo">↶ 戻す</button><button id="graph-redo">↷ やり直す</button><button id="graph-delete">選択を削除</button><button id="graph-minus" aria-label="縮小">−</button><span id="graph-zoom">100%</span><button id="graph-plus" aria-label="拡大">＋</button><button id="graph-home">全体を表示</button><span id="graph-connect" role="status"></span></div><div class="graph-scroll" tabindex="0" aria-label="ノードの作業領域"><div class="graph-size"><div class="graph-canvas"><svg class="graph-wires" width="4000" height="2400" aria-label="ノードの接続線"></svg><div class="graph-nodes"></div></div></div></div></section>';
 const $=s=>host.querySelector(s),scroll=$('.graph-scroll'),canvas=$('.graph-canvas'),nodes=$('.graph-nodes'),svg=$('.graph-wires');
 const checkpoint=()=>{history.push(structuredClone(graph));if(history.length>100)history.shift();redo.length=0;$('#graph-undo').disabled=false;$('#graph-redo').disabled=true;};
 const button=(text,fn)=>{const b=document.createElement('button');b.textContent=text;b.onclick=fn;return b;};
 const label=(text,control)=>{const l=document.createElement('label');l.append(document.createTextNode(text),control);return l;};
 function selectNode(id){selected=id;for(const el of nodes.children)el.classList.toggle('selected',el.dataset.id===id);$('#graph-delete').disabled=!id;}
 function commitParam(n,k,value){checkpoint();n.params[k]=value;notice('設定を変更しました');}
 function selectInput(n,k,options){const el=document.createElement('select');el.setAttribute('aria-label',TYPES[n.type].name+' '+k);for(const [text,value]of options){const o=document.createElement('option');o.textContent=text;o.value=value;el.append(o);}el.value=String(n.params[k]);el.onchange=()=>commitParam(n,k,['target','other'].includes(k)?Number(el.value):el.value);return el;}
 function render(){nodes.replaceChildren();pending=null;$('#graph-connect').textContent='';
 for(const n of graph.nodes){const def=TYPES[n.type],el=document.createElement('article');el.className='graph-node '+(def.event?'event-node':n.type==='branch'?'branch-node':'action-node');el.dataset.id=n.id;el.style.left=n.x+'px';el.style.top=n.y+'px';const head=document.createElement('div');head.className='node-heading';head.textContent=def.name;head.title='ドラッグして移動';el.append(head);el.addEventListener('pointerdown',()=>selectNode(n.id));
 head.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();checkpoint();const x=e.clientX,y=e.clientY,ox=n.x,oy=n.y;head.setPointerCapture(e.pointerId);head.onpointermove=ev=>{n.x=Math.max(0,Math.min(3700,ox+(ev.clientX-x)/zoom));n.y=Math.max(0,Math.min(2000,oy+(ev.clientY-y)/zoom));el.style.left=n.x+'px';el.style.top=n.y+'px';draw();};head.onpointerup=()=>{head.onpointermove=null;head.onpointerup=null;};};
 const ports=document.createElement('div');ports.className='node-ports';if(!def.event)ports.append(pin(n,'in','実行入力'));else ports.append(document.createElement('span'));const out=document.createElement('div');for(const port of outputs(n))out.append(pin(n,port,port==='yes'?'はい':port==='no'?'いいえ':'次へ'));ports.append(out);el.append(ports);
 const body=document.createElement('div');body.className='node-fields';const p=n.params;
 if(n.type==='branch')body.append(label('条件',selectInput(n,'condition',[['キーを押している','key'],['2つの形が重なる','touching'],['得点が指定値以上','score']])));
 if('key'in p)body.append(label('キー',selectInput(n,'key',KEYS)));
 for(const k of ['target','other'])if(k in p){const opts=getObjects().map((o,i)=>[(i+1)+'：'+o.userData.label,String(i+1)]);if(!opts.some(([,v])=>v===String(p[k])))opts.push(['対象を選択してください',String(p[k])]);body.append(label(k==='target'?'対象の形':'相手の形',selectInput(n,k,opts)));}
 if('x'in p){const row=document.createElement('div');row.className='node-xyz';for(const k of ['x','y','z'])row.append(numberField(n,k,k.toUpperCase()));body.append(row);if(n.type!=='position'){const cb=document.createElement('input');cb.type='checkbox';cb.checked=!!p.perSecond;cb.onchange=()=>commitParam(n,'perSecond',cb.checked);body.append(label(n.type==='rotate'?'度／秒（毎フレーム用）':'m／秒（毎フレーム用）',cb));}}
 if('amount'in p)body.append(numberField(n,'amount',n.type==='branch'?'得点のしきい値':'増やす数'));
 if('color'in p){const c=document.createElement('input');c.type='color';c.value=p.color;c.setAttribute('aria-label','ノードの色');c.onchange=()=>commitParam(n,'color',c.value);body.append(label('色',c));}
 if('text'in p){const input=document.createElement('input');input.value=p.text;input.maxLength=500;input.setAttribute('aria-label','表示するメッセージ');input.onchange=()=>commitParam(n,'text',input.value);body.append(input);}
 if(n.type==='branch'){const hint=document.createElement('small');hint.textContent='選んだ条件の設定だけを使います';body.append(hint);}el.append(body);nodes.append(el);
 }
 selectNode(selected);requestAnimationFrame(draw);$('#graph-undo').disabled=!history.length;$('#graph-redo').disabled=!redo.length;
 }
 function numberField(n,k,text){const input=document.createElement('input');input.type='number';input.step='any';input.min=-100000;input.max=100000;input.value=n.params[k];input.setAttribute('aria-label',TYPES[n.type].name+' '+text);input.onchange=()=>{const value=Number(input.value);if(input.value===''||!Number.isFinite(value)||Math.abs(value)>100000){input.value=n.params[k];return;}commitParam(n,k,value);};return label(text,input);}
 function pin(n,port,text){const b=document.createElement('button');b.className='node-pin '+(port==='in'?'input-pin':'output-pin');b.dataset.node=n.id;b.dataset.port=port;b.setAttribute('aria-label',TYPES[n.type].name+' '+n.id+' '+text);b.textContent=port==='in'?'○':text+' ○';b.title=port==='in'?'出力を選んでからクリック':'ここから次のノードの入力へ接続';
 b.onpointerdown=e=>{e.stopPropagation();if(port!=='in'){pending={from:n.id,port};$('#graph-connect').textContent='接続先の ○ をクリック（Escで取消）';}};
 b.onclick=e=>{e.stopPropagation();if(port==='in'&&pending)connect(n.id);else if(port!=='in'){pending={from:n.id,port};$('#graph-connect').textContent='接続先の ○ をクリック（Escで取消）';}};return b;}
 function connect(to){const edge={...pending,to};try{const next={nodes:graph.nodes,edges:[...graph.edges.filter(e=>e.from!==edge.from||e.port!==edge.port),edge]};validateGraph(next);checkpoint();graph=structuredClone(next);pending=null;render();notice('ノードをつなぎました。線をクリックすると切断できます。');}catch(e){pending=null;$('#graph-connect').textContent='';notice(e.message);}}
 window.addEventListener('pointerup',e=>{if(!pending||!host.isConnected)return;const pin=document.elementFromPoint(e.clientX,e.clientY)?.closest('.input-pin');if(pin&&host.contains(pin))connect(pin.dataset.node);});
 function draw(){svg.replaceChildren();for(const edge of graph.edges){const from=[...nodes.querySelectorAll('.node-pin')].find(el=>el.dataset.node===edge.from&&el.dataset.port===edge.port),to=[...nodes.querySelectorAll('.input-pin')].find(el=>el.dataset.node===edge.to);if(!from||!to)continue;const c=canvas.getBoundingClientRect(),a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x=(a.right-c.left)/zoom,y=(a.top+a.height/2-c.top)/zoom,xx=(b.left-c.left)/zoom,yy=(b.top+b.height/2-c.top)/zoom;const path=document.createElementNS('http://www.w3.org/2000/svg','path');const bend=Math.max(60,Math.abs(xx-x)*.5);path.setAttribute('d',`M${x} ${y} C${x+bend} ${y},${xx-bend} ${yy},${xx} ${yy}`);path.classList.add('wire',edge.port);path.setAttribute('tabindex','0');path.setAttribute('role','button');path.setAttribute('aria-label','接続を削除 '+edge.from+' → '+edge.to);const cut=()=>{checkpoint();graph.edges=graph.edges.filter(e=>e!==edge);render();notice('接続を外しました');};path.onclick=cut;path.onkeydown=e=>{if(e.key==='Enter'||e.key==='Delete'){e.preventDefault();cut();}};svg.append(path);}}
 function add(type){if(graph.nodes.length>=300){notice('ノードは300個までです');return;}checkpoint();const n={id:'node-'+(++serial),type,x:Math.round(scroll.scrollLeft/zoom+80+(graph.nodes.length%3)*30),y:Math.round(scroll.scrollTop/zoom+60+(graph.nodes.length%3)*50),params:structuredClone(TYPES[type].defaults)};n.x=Math.min(n.x,3600);n.y=Math.min(n.y,1900);graph.nodes.push(n);selected=n.id;render();}
 function palette(){const query=$('#node-search').value.trim();$('#node-types').replaceChildren();for(const group of ['イベント','形','条件','ゲーム']){const matches=Object.entries(TYPES).filter(([,v])=>v.group===group&&v.name.includes(query));if(!matches.length)continue;const title=document.createElement('h4');title.textContent=group;$('#node-types').append(title);for(const [type,v]of matches)$('#node-types').append(button('＋ '+v.name,()=>add(type)));}}
 $('#node-search').oninput=palette;palette();
 const undo=()=>{if(!history.length)return;redo.push(structuredClone(graph));graph=history.pop();render();};const redoAction=()=>{if(!redo.length)return;history.push(structuredClone(graph));graph=redo.pop();render();};
 $('#graph-undo').onclick=undo;$('#graph-redo').onclick=redoAction;
 const remove=()=>{if(!selected)return;checkpoint();graph.nodes=graph.nodes.filter(n=>n.id!==selected);graph.edges=graph.edges.filter(e=>e.from!==selected&&e.to!==selected);selected=null;render();};$('#graph-delete').onclick=remove;
 function setZoom(v){zoom=Math.max(.4,Math.min(1.5,v));canvas.style.transform=`scale(${zoom})`;$('.graph-size').style.width=4000*zoom+'px';$('.graph-size').style.height=2400*zoom+'px';$('#graph-zoom').textContent=Math.round(zoom*100)+'%';draw();}
 $('#graph-minus').onclick=()=>setZoom(zoom-.1);$('#graph-plus').onclick=()=>setZoom(zoom+.1);$('#graph-home').onclick=()=>{const width=Math.max(800,...graph.nodes.map(n=>n.x+300)),height=Math.max(400,...graph.nodes.map(n=>n.y+320));setZoom(Math.min(1,scroll.clientWidth/width,scroll.clientHeight/height));scroll.scrollTo(0,0);};
 scroll.onpointerdown=e=>{if(e.target.closest('.graph-node,.wire'))return;selected=null;selectNode(null);const sx=scroll.scrollLeft,sy=scroll.scrollTop,x=e.clientX,y=e.clientY;scroll.setPointerCapture(e.pointerId);scroll.onpointermove=ev=>{scroll.scrollLeft=sx+x-ev.clientX;scroll.scrollTop=sy+y-ev.clientY;};scroll.onpointerup=()=>{scroll.onpointermove=null;};};
 host.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();e.shiftKey?redoAction():undo();}if(e.key==='Delete'){e.preventDefault();remove();}if(e.key==='Escape'){pending=null;$('#graph-connect').textContent='';}});
 const api={save:()=>structuredClone(graph),load(value){graph=validateGraph(value);serial=Math.max(serial,...graph.nodes.map(n=>Number(n.id.replace('node-',''))||0));history.length=0;redo.length=0;selected=null;render();},refresh:render,validate:()=>validateGraph(graph,getObjects().length),example(target=1){checkpoint();graph={nodes:[{id:'node-'+(++serial),type:'key',x:50,y:80,params:{key:'ArrowRight'}},{id:'node-'+(++serial),type:'move',x:380,y:80,params:{target,x:1,y:0,z:0,perSecond:false}},{id:'node-'+(++serial),type:'score',x:710,y:80,params:{amount:1}}],edges:[]};graph.edges=[{from:graph.nodes[0].id,port:'next',to:graph.nodes[1].id},{from:graph.nodes[1].id,port:'next',to:graph.nodes[2].id}];selected=null;setZoom(1);scroll.scrollTo(0,0);render();}};
 render();return api;
}
