import {TYPES,KEYS,CONTEXT,outputs,validateGraph} from './graph-core.js';
export function createGraphEditor(host,getObjects,notice){
 let graph={nodes:[],edges:[]},selected=null,pending=null,serial=0,zoom=1;const history=[],redo=[];
 host.innerHTML='<aside class="node-palette"><h3>ノードを追加</h3><input id="node-search" aria-label="ノードを検索" placeholder="ノードを検索"><div id="node-types"></div><p>出力の ○ → 入力の ○ をクリック、またはドラッグで接続。線をクリックして切断。</p></aside><section class="graph-area"><div class="graph-tools"><button id="graph-undo">↶ 戻す</button><button id="graph-redo">↷ やり直す</button><button id="graph-delete">選択を削除</button><button id="graph-minus" aria-label="縮小">−</button><span id="graph-zoom">100%</span><button id="graph-plus" aria-label="拡大">＋</button><button id="graph-home">全体を表示</button><span id="graph-connect" role="status"></span></div><div class="graph-scroll" tabindex="0" aria-label="ノードの作業領域"><div class="graph-size"><div class="graph-canvas"><svg class="graph-wires" width="4000" height="2400" aria-label="ノードの接続線"></svg><div class="graph-nodes"></div></div></div></div></section>';
 const $=s=>host.querySelector(s),scroll=$('.graph-scroll'),canvas=$('.graph-canvas'),nodes=$('.graph-nodes'),svg=$('.graph-wires');
 const checkpoint=()=>{history.push(structuredClone(graph));if(history.length>100)history.shift();redo.length=0;$('#graph-undo').disabled=false;$('#graph-redo').disabled=true;};
 const button=(text,fn)=>{const b=document.createElement('button');b.textContent=text;b.onclick=fn;return b;};
 const label=(text,control)=>{const l=document.createElement('label');l.append(document.createTextNode(text),control);return l;};
 function selectNode(id){selected=id;for(const el of nodes.children)el.classList.toggle('selected',el.dataset.id===id);$('#graph-delete').disabled=!id;}
 function commitParam(n,k,value){checkpoint();n.params[k]=value;notice('設定を変更しました');if(['condition','kind'].includes(k))render();}
 function selectInput(n,k,options){const el=document.createElement('select');el.setAttribute('aria-label',TYPES[n.type].name+' '+k);for(const [text,value]of options){const o=document.createElement('option');o.textContent=text;o.value=value;el.append(o);}el.value=String(n.params[k]);el.onchange=()=>commitParam(n,k,typeof TYPES[n.type].defaults[k]==='number'?Number(el.value):el.value);return el;}
 function render(){nodes.replaceChildren();pending=null;$('#graph-connect').textContent='';
 for(const n of graph.nodes){const def=TYPES[n.type],el=document.createElement('article');el.className='graph-node '+(def.event?'event-node':n.type==='branch'?'branch-node':'action-node');el.dataset.id=n.id;el.style.left=n.x+'px';el.style.top=n.y+'px';const head=document.createElement('div');head.className='node-heading';head.textContent=def.name;head.title='ドラッグして移動';el.append(head);el.addEventListener('pointerdown',()=>selectNode(n.id));
 head.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();checkpoint();const x=e.clientX,y=e.clientY,ox=n.x,oy=n.y;head.setPointerCapture(e.pointerId);head.onpointermove=ev=>{n.x=Math.max(0,Math.min(3700,ox+(ev.clientX-x)/zoom));n.y=Math.max(0,Math.min(2000,oy+(ev.clientY-y)/zoom));el.style.left=n.x+'px';el.style.top=n.y+'px';draw();};head.onpointerup=()=>{head.onpointermove=null;head.onpointerup=null;};};
 const ports=document.createElement('div');ports.className='node-ports';if(!def.event)ports.append(pin(n,'in','実行入力'));else ports.append(document.createElement('span'));const out=document.createElement('div');for(const port of outputs(n))out.append(pin(n,port,port==='yes'?'はい':port==='no'?'いいえ':port==='body'?'くり返す':'次へ'));ports.append(out);el.append(ports);
 const body=document.createElement('div');body.className='node-fields';const p=n.params;
 for(const field of def.fields){const {key:k,kind,options}=field;let text=field.label;
 if(['branch','condition_event'].includes(n.type)){const keep={key:['condition','key','mode'],touching:['condition','target','other','mode'],score:['condition','amount','mode'],compare:['condition','a','op','b','mode']}[p.condition];if(!keep.includes(k))continue;}
 if(n.type==='ui_create'&&k==='options'&&p.kind!=='select')continue;
 if(kind==='select')body.append(label(text,selectInput(n,k,options)));
 else if(['target','eventTarget'].includes(kind)){const opts=targetOptions(def.event,kind==='eventTarget');if(!opts.some(([,v])=>String(v)===String(p[k])))opts.push(['対象を選択してください',p[k]]);body.append(label(text,selectInput(n,k,opts)));}
 else if(['number','value'].includes(kind))body.append(valueField(n,k,text,kind==='number'));
 else if(kind==='boolean'){const cb=document.createElement('input');cb.type='checkbox';cb.checked=p[k];cb.onchange=()=>commitParam(n,k,cb.checked);body.append(label(text,cb));}
 else{const input=document.createElement('input');input.type=kind==='color'?'color':'text';input.value=p[k];input.maxLength=kind==='name'?64:500;input.setAttribute('aria-label',def.name+' '+text);input.onchange=()=>commitParam(n,k,input.value);body.append(label(text,input));}
 }
 el.append(body);nodes.append(el);
 }
 selectNode(selected);requestAnimationFrame(draw);$('#graph-undo').disabled=!history.length;$('#graph-redo').disabled=!redo.length;
 }
 function targetOptions(event=false,all=false){return [...(all?[['画面全体／すべての形',0],['すべての形（背景を除く）',-1]]:[]),...(!event?[['イベントの対象',-1],['イベントの相手',-2],['今作成した形',-3]]:[]),...getObjects().map((o,i)=>[(i+1)+'：'+o.userData.label,i+1])];}
 function valueField(n,k,text,numeric){const wrap=document.createElement('div');wrap.className='node-value';const v=n.params[k],bound=v&&typeof v==='object';const source=document.createElement('select');source.setAttribute('aria-label',TYPES[n.type].name+' '+text+'の値の種類');const mode=bound?v.source:typeof v==='number'?'number':typeof v==='boolean'?'boolean':'text';for(const [title,id]of [...(numeric?[['固定値','number']]:[['数値','number'],['文字','text'],['真偽値','boolean']]),['変数','variable'],['イベントの値','event'],['形の座標','object']]){const o=document.createElement('option');o.textContent=title;o.value=id;source.append(o);}source.value=mode;source.onchange=()=>{const type=source.value;commitParam(n,k,type==='number'?0:type==='text'?'':type==='boolean'?false:type==='variable'?{source:type,name:'value'}:type==='event'?{source:type,field:'value'}:{source:type,target:1,field:'x'});render();};wrap.append(label(text,source));
 const input=document.createElement('input');input.setAttribute('aria-label',TYPES[n.type].name+' '+text);
 if(!bound){if(mode==='boolean'){input.type='checkbox';input.checked=v;input.onchange=()=>commitParam(n,k,input.checked);}else{input.type=mode==='number'?'number':'text';input.step='any';input.value=v;input.maxLength=500;input.onchange=()=>{const value=mode==='number'?Number(input.value):input.value;if(mode==='number'&&(input.value===''||!Number.isFinite(value)||Math.abs(value)>100000)){input.value=v;return;}commitParam(n,k,value);};}wrap.append(input);}
 else if(v.source==='variable'){input.value=v.name;input.maxLength=64;input.placeholder='変数名';input.onchange=()=>commitParam(n,k,{...v,name:input.value});wrap.append(input);}
 else{const opts=v.source==='event'?CONTEXT:[['X座標','x'],['Y座標','y'],['Z座標','z']];const fields=document.createElement('select');fields.setAttribute('aria-label',TYPES[n.type].name+' '+text+'の参照項目');for(const [title,id]of opts){const o=document.createElement('option');o.textContent=title;o.value=id;fields.append(o);}fields.value=v.field;fields.onchange=()=>commitParam(n,k,{...n.params[k],field:fields.value});wrap.append(fields);if(v.source==='object'){const targets=document.createElement('select');targets.setAttribute('aria-label',text+'の参照対象');for(const [title,id]of targetOptions()){const o=document.createElement('option');o.textContent=title;o.value=id;targets.append(o);}targets.value=v.target;targets.onchange=()=>commitParam(n,k,{...n.params[k],target:Number(targets.value)});wrap.append(targets);}}
 return wrap;
 }
 function pin(n,port,text){const b=document.createElement('button');b.className='node-pin '+(port==='in'?'input-pin':'output-pin');b.dataset.node=n.id;b.dataset.port=port;b.setAttribute('aria-label',TYPES[n.type].name+' '+n.id+' '+text);b.textContent=port==='in'?'○':text+' ○';b.title=port==='in'?'出力を選んでからクリック':'ここから次のノードの入力へ接続';
 b.onpointerdown=e=>{e.stopPropagation();if(port!=='in'){pending={from:n.id,port};$('#graph-connect').textContent='接続先の ○ をクリック（Escで取消）';}};
 b.onclick=e=>{e.stopPropagation();if(port==='in'&&pending)connect(n.id);else if(port!=='in'){pending={from:n.id,port};$('#graph-connect').textContent='接続先の ○ をクリック（Escで取消）';}};return b;}
 function connect(to){const edge={...pending,to};try{const next={nodes:graph.nodes,edges:[...graph.edges.filter(e=>e.from!==edge.from||e.port!==edge.port),edge]};validateGraph(next);checkpoint();graph=structuredClone(next);pending=null;render();notice('ノードをつなぎました。線をクリックすると切断できます。');}catch(e){pending=null;$('#graph-connect').textContent='';notice(e.message);}}
 window.addEventListener('pointerup',e=>{if(!pending||!host.isConnected)return;const pin=document.elementFromPoint(e.clientX,e.clientY)?.closest('.input-pin');if(pin&&host.contains(pin))connect(pin.dataset.node);});
 function draw(){svg.replaceChildren();for(const edge of graph.edges){const from=[...nodes.querySelectorAll('.node-pin')].find(el=>el.dataset.node===edge.from&&el.dataset.port===edge.port),to=[...nodes.querySelectorAll('.input-pin')].find(el=>el.dataset.node===edge.to);if(!from||!to)continue;const c=canvas.getBoundingClientRect(),a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x=(a.right-c.left)/zoom,y=(a.top+a.height/2-c.top)/zoom,xx=(b.left-c.left)/zoom,yy=(b.top+b.height/2-c.top)/zoom;const path=document.createElementNS('http://www.w3.org/2000/svg','path');const bend=Math.max(60,Math.abs(xx-x)*.5);path.setAttribute('d',`M${x} ${y} C${x+bend} ${y},${xx-bend} ${yy},${xx} ${yy}`);path.classList.add('wire',edge.port);path.setAttribute('tabindex','0');path.setAttribute('role','button');path.setAttribute('aria-label','接続を削除 '+edge.from+' → '+edge.to);const cut=()=>{checkpoint();graph.edges=graph.edges.filter(e=>e!==edge);render();notice('接続を外しました');};path.onclick=cut;path.onkeydown=e=>{if(e.key==='Enter'||e.key==='Delete'){e.preventDefault();cut();}};svg.append(path);}}
 function add(type){if(graph.nodes.length>=300){notice('ノードは300個までです');return;}checkpoint();const n={id:'node-'+(++serial),type,x:Math.round(scroll.scrollLeft/zoom+80+(graph.nodes.length%3)*30),y:Math.round(scroll.scrollTop/zoom+60+(graph.nodes.length%3)*50),params:structuredClone(TYPES[type].defaults)};n.x=Math.min(n.x,3600);n.y=Math.min(n.y,1900);graph.nodes.push(n);selected=n.id;render();}
 function palette(){const query=$('#node-search').value.trim();$('#node-types').replaceChildren();for(const group of ['イベント','形','条件','変数・計算','制御','画面UI','ゲーム']){const matches=Object.entries(TYPES).filter(([,v])=>v.group===group&&v.name.includes(query));if(!matches.length)continue;const title=document.createElement('h4');title.textContent=group;$('#node-types').append(title);for(const [type,v]of matches)$('#node-types').append(button('＋ '+v.name,()=>add(type)));}}
 $('#node-search').oninput=palette;palette();
 const undo=()=>{if(!history.length)return;redo.push(structuredClone(graph));graph=history.pop();render();};const redoAction=()=>{if(!redo.length)return;history.push(structuredClone(graph));graph=redo.pop();render();};
 $('#graph-undo').onclick=undo;$('#graph-redo').onclick=redoAction;
 const remove=()=>{if(!selected)return;checkpoint();graph.nodes=graph.nodes.filter(n=>n.id!==selected);graph.edges=graph.edges.filter(e=>e.from!==selected&&e.to!==selected);selected=null;render();};$('#graph-delete').onclick=remove;
 function setZoom(v){zoom=Math.max(.4,Math.min(1.5,v));canvas.style.transform=`scale(${zoom})`;$('.graph-size').style.width=4000*zoom+'px';$('.graph-size').style.height=2400*zoom+'px';$('#graph-zoom').textContent=Math.round(zoom*100)+'%';draw();}
 $('#graph-minus').onclick=()=>setZoom(zoom-.1);$('#graph-plus').onclick=()=>setZoom(zoom+.1);$('#graph-home').onclick=()=>{const width=Math.max(800,...graph.nodes.map(n=>n.x+300)),height=Math.max(400,...graph.nodes.map(n=>n.y+320));setZoom(Math.min(1,scroll.clientWidth/width,scroll.clientHeight/height));scroll.scrollTo(0,0);};
 scroll.onpointerdown=e=>{if(e.target.closest('.graph-node,.wire'))return;selected=null;selectNode(null);const sx=scroll.scrollLeft,sy=scroll.scrollTop,x=e.clientX,y=e.clientY;scroll.setPointerCapture(e.pointerId);scroll.onpointermove=ev=>{scroll.scrollLeft=sx+x-ev.clientX;scroll.scrollTop=sy+y-ev.clientY;};scroll.onpointerup=()=>{scroll.onpointermove=null;};};
 host.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();e.shiftKey?redoAction():undo();}if(e.key==='Delete'){e.preventDefault();remove();}if(e.key==='Escape'){pending=null;$('#graph-connect').textContent='';}});
 const api={save:()=>structuredClone(graph),load(value){graph=validateGraph(value);serial=Math.max(serial,...graph.nodes.map(n=>Number(n.id.replace('node-',''))||0));history.length=0;redo.length=0;selected=null;render();},refresh:render,validate:()=>validateGraph(graph,getObjects().length),example(target=1,kind='key'){checkpoint();graph={nodes:[],edges:[]};const add=(type,x,y,params={})=>{const n={id:'node-'+(++serial),type,x,y,params:{...structuredClone(TYPES[type].defaults),...params}};graph.nodes.push(n);return n.id;};const link=(a,b,port='next')=>graph.edges.push({from:a,to:b,port});
 if(kind==='held'||kind==='mouseheld'){const e=add(kind==='held'?'keyheld':'pointer',50,70,kind==='held'?{key:'ArrowRight'}:{kind:'held',target:0,button:0});const m=add('move',390,70,{target,x:2,y:0,z:0,perSecond:true});link(e,m);}
 else if(kind==='click'){const e=add('pointer',50,70,{kind:'click',target:-1});const c=add('color',390,70,{target:-1,color:'#44cc88'});link(e,c);notice('形をクリックすると、その形が緑色になります。');}
 else if(kind==='timer'){const t=add('timer',40,60,{seconds:1});const v=add('variable',365,60,{name:'seconds',mode:'add',value:1});const say=add('say',690,60,{text:{source:'variable',name:'seconds'}});link(t,v);link(v,say);}
 else if(kind==='ui'){const e=add('start',40,40),q=add('prompt',370,40,{name:'answer',text:'好きなゲームの名前は？'});link(e,q);const a=add('answer',40,390,{name:'answer'}),say=add('say',370,390,{text:{source:'event',field:'value'}});link(a,say);}
 else if(kind==='function'){const e=add('key',40,40),r=add('repeat',370,40,{count:3}),call=add('call',700,40,{name:'step'}),fn=add('function',40,450,{name:'step'}),m=add('move',370,450,{target,x:.3}),w=add('wait',700,450,{seconds:.2});link(e,r);link(r,call,'body');link(fn,m);link(m,w);}
 else{const e=add('key',50,80),m=add('move',380,80,{target}),score=add('score',710,80);link(e,m);link(m,score);}
 selected=null;setZoom(1);scroll.scrollTo(0,0);render();}};

 render();return api;
}
